Repository labring/laf, pull requests merged in 2023-07, with the labels that each got.

#1343 feat(web): support function rename
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/TriggerModal/index.tsx
Labels: size/M

#1336 feat(server): support function rename
  server/src/function/dto/update-function.dto.ts
  server/src/function/function.controller.ts
  server/src/function/function.module.ts
  server/src/function/function.service.ts
  server/src/trigger/trigger.controller.ts
  server/src/trigger/trigger.service.ts
Labels: size/L

#1352 fix(server): Fix cross-database issues with function templates
  server/src/function-template/function-template.service.ts
  server/src/function/function.service.ts
Labels: size/M

#1353 doc: update ServerDocking.md
  docs/3min/wechat/MediaPlatform/ServerDocking.md
Labels: size/XS

#1351 fix(web):fix header mobile adaptation
  web/src/layouts/Header/index.tsx
  web/src/pages/auth/signin/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/tailwind.config.cjs
Labels: size/L

#1349 feat(cli): app init support schemaOnly
  cli/src/action/application/index.ts
  cli/src/command/application/index.ts
Labels: size/XS

#1356 feat(web): support modifying user info (username, phone, avatar)
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/auth.ts
  web/src/apis/v1/user.ts
  web/src/components/CommonIcon/index.tsx
  web/src/components/SectionList/index.module.scss
  web/src/components/SectionList/index.tsx
  web/src/components/SendSmsCodeButton/index.tsx
  web/src/layouts/Header/UserSetting/index.tsx
  web/src/layouts/Header/index.tsx
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/AppEnvList/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/UserInfo/Mods/AvatarEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/EmailEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/PasswordEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/UsernameEditor.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/setting/UserInfo/service.ts
  web/src/pages/app/setting/index.tsx
  web/src/pages/auth/reset-password/index.tsx
  web/src/pages/globalStore.ts
  web/src/utils/getAvatarUrl.ts
Labels: size/XXL

#1355 feat(server): support modifying user info (username, phone, avatar)
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/authentication/authentication.controller.ts
  server/src/authentication/authentication.module.ts
  server/src/authentication/dto/bind-phone.dto.ts
  server/src/authentication/dto/bind-username.dto.ts
  server/src/main.ts
  server/src/user/dto/bind-phone.dto.ts
  server/src/user/dto/bind-username.dto.ts
  server/src/user/dto/update-avatar.dto.ts
  server/src/user/entities/user-avatar.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: size/L

#1359 feat(web): add balance info at header
  web/index.html
  web/src/App.tsx
  web/src/components/ChargeButton/index.tsx
  web/src/layouts/Header/UserBalance/index.tsx
  web/src/layouts/Header/index.tsx
  web/src/pages/homepage/language.tsx
  web/src/utils/format.ts
Labels: size/M

#1361 fix(web): header width
  web/src/layouts/Header/index.tsx
Labels: size/XS

#1362 fix(web): fix toast & bill overflow
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/UserInfo/Mods/UsernameEditor.tsx
Labels: size/XS

#1360 fix(cli): get website id by `_id` property
  cli/src/action/website/index.ts
Labels: size/XS

#1366 chore(web): sort bundles with createdAt & add copytext on…
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/S

#1367 fix(web): auto flush cache from service worker
  web/index.html
  web/vite.config.ts
Labels: size/XS

#1364 fix(web): storage file list hidden (#1363)
  web/src/pages/app/storages/mods/FileList/index.tsx
Labels: size/XS

#1369 fix(web): fix function template darkmode & fix function spacing
  web/src/components/SectionList/index.module.scss
  web/src/layouts/Template.tsx
  web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/UsernameEditor.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/auth/reset-password/index.tsx
Labels: size/M

#1371 feat(web): add billing center
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/App.css
  web/src/apis/v1/accounts.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/apps.ts
  web/src/apis/v1/billings.ts
  web/src/apis/v1/user.ts
  web/src/components/CommonIcon/index.tsx
  web/src/components/ConfirmButton/index.tsx
  web/src/components/DateRangePicker/index.tsx
  web/src/components/SectionList/index.module.scss
  web/src/components/SectionList/index.tsx
  web/src/layouts/Header/UserBalance/index.tsx
  web/src/layouts/Header/UserSetting/index.tsx
  web/src/layouts/Header/index.tsx
  web/src/layouts/Template.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/EditDomain.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/service.ts
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/AppEnvList/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/setting/BillingDetails/index.tsx
  web/src/pages/app/setting/CardRedemption/index.tsx
  web/src/pages/app/setting/CardRedemption/service.ts
  web/src/pages/app/setting/CustomDomain/index.tsx
  web/src/pages/app/setting/CustomDomain/service.ts
  web/src/pages/app/setting/PATList/index.tsx
  web/src/pages/app/setting/PricingStandards/PricingCard.tsx
  web/src/pages/app/setting/PricingStandards/index.tsx
  web/src/pages/app/setting/RechargeHistory/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/UserInfo/Mods/AvatarEditor.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/setting/UserInvite/index.tsx
  web/src/pages/app/setting/UserInvite/service.ts
  web/src/pages/app/setting/UserSetting/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/functionTemplate/Mods/PaginationBar/index.tsx
  web/src/pages/home/mods/StatusBadge/index.tsx
  web/tailwind.config.cjs
Labels: size/XXL

#1372 fix(web): delete unused api
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/pat2token.ts
  web/src/apis/v1/profile.ts
Labels: size/M

#1374 feat(web): the collection supports Mongo where statements.
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/database/index.tsx
  web/src/pages/app/database/service.ts
Labels: size/M

#1377 fix(web): Type error "strict"
  web/package-lock.json
  web/src/pages/app/database/service.ts
Labels: size/XS

#1376 chore: add auto updater for sync-upstream.yml
  .github/workflows/sync-upstream.yml
Labels: size/M

#1375 refactor(web): modify the redirection after signup to dashboard & add a loading state for the query
  web/src/components/DateRangePicker/index.tsx
  web/src/pages/app/setting/BillingDetails/index.tsx
  web/src/pages/app/setting/RechargeHistory/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/UserInvite/index.tsx
  web/src/pages/auth/service.ts
  web/src/pages/auth/signup/index.tsx
Labels: size/L

#1378 fix(web): delete repeated component & fix usersetting & fix billing unit
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/components/CommonIcon/index.tsx
  web/src/components/Pagination/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/FunctionTemplate/index.tsx
  web/src/pages/app/mods/SideBar/index.module.scss
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/setting/BillingDetails/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/UserInvite/index.tsx
  web/src/pages/app/setting/UserSetting/index.tsx
  web/src/pages/functionTemplate/Mods/PaginationBar/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
  web/src/pages/functionTemplate/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/utils/format.ts
Labels: size/L

#1379 fix(server): add invite code chargeOrder invite code profit settings
  server/src/account/entities/account-charge-order.ts
  server/src/account/entities/invitation-profit-amount.ts
  server/src/authentication/phone/phone.service.ts
  server/src/authentication/user-passwd/user-password.service.ts
Labels: size/M

#1380 feat(server): function templates add user avatar support
  server/src/function-template/dto/function-template-usedBy.dto.ts
  server/src/function-template/dto/function-templates.dto.ts
  server/src/function-template/function-template.controller.ts
  server/src/function-template/function-template.service.ts
Labels: size/L

#1383 fix(server): fix invite code profit settings
  server/src/authentication/phone/phone.service.ts
  server/src/authentication/user-passwd/user-password.service.ts
  server/src/setting/entities/setting.ts
Labels: size/XS

#1384 refactor(server): date String type to number
  server/src/account/account.controller.ts
  server/src/billing/billing.controller.ts
Labels: size/S

#1382 fix(web): fix ui & date range
  web/src/components/DateRangePicker/index.tsx
  web/src/pages/app/setting/AppEnvList/index.tsx
  web/src/pages/app/setting/AppInfoList/InfoDetail/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/home/mods/StatusBadge/index.tsx
Labels: size/L

#1387 Change the delete IconText color to red and completion the error color
  web/src/chakraTheme.ts
  web/src/chakraThemeDark.ts
  web/src/components/IconText/index.tsx
  web/src/pages/app/database/PolicyListPanel/index.tsx
  web/src/pages/app/database/mods/DeleteCollectionModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/storages/mods/DeleteBucketModal/index.tsx
  web/tailwind.config.cjs
Labels: size/M

#1394 feat(server): add random username for phone signup
  server/src/authentication/phone/phone.service.ts
Labels: size/XS

#1397 fix(server): change giftcode dto string length
  server/src/account/dto/use-gift-code.dto.ts
Labels: size/XS

#1395 refactor(server): add template user infomation
  server/src/function-template/dto/function-templates.dto.ts
  server/src/function-template/function-template.service.ts
Labels: size/M

#1392 refactor(web): use react-hook-form & modify styles & add laf-ai apply button
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/Markdown/index.tsx
  web/src/components/SendSmsCodeButton/index.tsx
  web/src/components/SmsCodeInput/index.tsx
  web/src/layouts/Auth/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/setting/UserInfo/Mods/PasswordEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/UsernameEditor.tsx
  web/src/pages/auth/reset-password/index.tsx
  web/src/pages/auth/signin/mods/LoginByPasswordPanel/index.tsx
  web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
  web/src/pages/auth/signup/index.tsx
Labels: size/L

#1381 feat: replace current logging solution with log server
  .github/workflows/dockerize-log-server.yml
  .prettierignore
  build/charts/laf-server/templates/_helpers.tpl
  build/charts/laf-server/templates/deployment.yaml
  build/charts/laf-server/templates/log-server.yaml
  build/charts/laf-server/values.yaml
  build/start.sh
  docs/en/guide/function/logs.md
  docs/guide/function/logs.md
  lerna.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/constants.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/support/function-engine/console.ts
  runtimes/nodejs/src/support/function-log.ts
  runtimes/nodejs/start.sh
  server/src/application/application.module.ts
  server/src/constants.ts
  server/src/function/function.module.ts
  server/src/function/function.service.ts
  server/src/initializer/initializer.service.ts
  server/src/instance/instance.service.ts
  server/src/region/entities/region.ts
  services/log-server/.dockerignore
  services/log-server/.gitignore
  services/log-server/.prettierrc
  services/log-server/Dockerfile
  services/log-server/commitlint.config.js
  services/log-server/package-lock.json
  services/log-server/package.json
  services/log-server/src/config.ts
  services/log-server/src/db.ts
  services/log-server/src/handler/add-function-log.ts
  services/log-server/src/handler/get-function-log.ts
  services/log-server/src/helper/ensure-collection-exist.ts
  services/log-server/src/helper/verify-appid.ts
  services/log-server/src/index.ts
  services/log-server/src/logger.ts
  services/log-server/tsconfig.json
Labels: size/XL

#1402 fix(web): fix reset phone smscode type
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/components/SendSmsCodeButton/index.tsx
  web/src/pages/app/setting/UserInfo/Mods/PasswordEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
  web/src/pages/auth/reset-password/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
  web/src/pages/functionTemplate/Mods/UseTemplateModal/index.tsx
Labels: size/M

#1396 feat(server): add recycle bin
  server/src/app.module.ts
  server/src/application/application.module.ts
  server/src/constants.ts
  server/src/function/function.controller.ts
  server/src/function/function.module.ts
  server/src/function/function.service.ts
  server/src/instance/instance.module.ts
  server/src/recycle-bin/cloud-function/dto/delete-recycle-bin-functions.dto.ts
  server/src/recycle-bin/cloud-function/dto/get-recycle-bin-functions.dto.ts
  server/src/recycle-bin/cloud-function/dto/restore-recycle-bin-functions.dto.ts
  server/src/recycle-bin/cloud-function/function-recycle-bin.controller.ts
  server/src/recycle-bin/cloud-function/function-recycle-bin.service.ts
  server/src/recycle-bin/cloud-function/interface/function-recycle-bin-query.interface.ts
  server/src/recycle-bin/entities/recycle-bin.ts
  server/src/recycle-bin/recycle-bin.module.ts
  server/src/trigger/trigger.module.ts
Labels: size/XL

#1398 feat(web): add functions recycle bin
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/apis/v1/accounts.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/billings.ts
  web/src/apis/v1/recycle-bin.ts
  web/src/components/CommonIcon/index.tsx
  web/src/components/SectionList/index.module.scss
  web/src/pages/app/mods/StatusBar/RecycleBinModal/index.tsx
  web/src/pages/app/mods/StatusBar/RecycleBinModal/service.ts
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/app/setting/RechargeHistory/index.tsx
  web/src/pages/app/setting/UserSetting/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddDependenceModal.tsx
  web/src/pages/functionTemplate/Mods/FunctionPopover/index.tsx
  web/tailwind.config.cjs
Labels: size/XL

#1405 fix(server): fix function template user information display
  server/src/function-template/function-template.service.ts
Labels: size/M

#1408 feat(cli): add options for laf dep command
  cli/src/action/dependency/index.ts
  cli/src/action/deploy/index.ts
  cli/src/command/dependency/index.ts
Labels: size/M

#1411 fix(web): fix display issue when username does not exist
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
Labels: size/M

#1406 feat(web): Increase the clickable area of the button
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/database/PolicyDataList/index.tsx
  web/src/pages/app/database/RightComponent/DeleteButton.tsx
Labels: size/M

#1403 feat(web): optimize the state of app
  web/src/constants/index.ts
  web/src/pages/globalStore.ts
  web/src/pages/home/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/pages/home/mods/StatusBadge/index.tsx
Labels: size/L

#1416 refactor(web): optimize create function & function template component
  web/src/components/CommonIcon/index.tsx
  web/src/constants/index.ts
  web/src/layouts/Header/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/functionTemplates.ts
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/FunctionTemplate/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/BillingDetails/index.tsx
  web/src/pages/app/setting/CardRedemption/index.tsx
  web/src/pages/app/setting/RechargeHistory/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddFunctionModal.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/index.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/FunctionPopover.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateCard/TemplateCard.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/UseTemplate/UseTemplateModal.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/UseTemplate/index.tsx
  web/src/pages/functionTemplate/index.module.scss
  web/src/pages/functionTemplate/index.tsx
  web/src/pages/globalStore.ts
  web/src/pages/home/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/utils/getAvatarUrl.ts
Labels: size/XL

#1414 feat(web): add functions list folder
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/FileTypeIcon/index.tsx
  web/src/components/SectionList/index.module.scss
  web/src/pages/app/database/PolicyDataList/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/logs/index.tsx
  web/src/pages/app/mods/StatusBar/RecycleBinModal/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/utils/format.ts
Labels: size/L

#1421 fix(log-server): miss log for request_id required
  services/log-server/src/handler/add-function-log.ts
  services/log-server/src/helper/verify-appid.ts
Labels: size/S

#1418 feat(web): support binding email
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/auth.ts
  web/src/apis/v1/user.ts
  web/src/chakraTheme.ts
  web/src/chakraThemeDark.ts
  web/src/components/SendEmailCodeButton/index.tsx
  web/src/components/SmsCodeInput/index.tsx
  web/src/pages/app/setting/UserInfo/AuthDetail/index.tsx
  web/src/pages/app/setting/UserInfo/Mods/EmailEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/PasswordEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
  web/src/pages/app/setting/UserInfo/Mods/UsernameEditor.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/setting/UserInfo/service.ts
  web/src/pages/auth/service.ts
Labels: size/XL

#1422 feat(web): add app realeasing status
  web/src/constants/index.ts
  web/src/pages/home/mods/StatusBadge/index.tsx
Labels: size/M

#1412 chore(server): add expired time for gift code
  server/src/account/account.controller.ts
  server/src/account/account.service.ts
  server/src/account/entities/account-gift-code.ts
Labels: size/S

#1413 feat(cli): impl trigger command
  cli/src/action/trigger/index.ts
  cli/src/command/trigger/index.ts
  cli/src/main.ts
Labels: size/L

#1419 feat: update laf cluster image to deploy laf in a sealos cluster.
  build/Kubefile
  build/start.sh
Labels: size/S

#1429 fix(web): fix template used by total number & template list query
  web/src/pages/functionTemplate/FuncTemplateItem/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
  web/src/pages/functionTemplate/index.tsx
Labels: size/M

#1417 feat(server): support binding email
  server/src/authentication/authentication.module.ts
  server/src/authentication/authentication.service.ts
  server/src/authentication/dto/email-verify-code.dto.ts
  server/src/authentication/dto/send-email-code.dto.ts
  server/src/authentication/email/email.controller.ts
  server/src/authentication/email/email.service.ts
  server/src/authentication/email/mailer.service.ts
  server/src/authentication/entities/email-verify-code.ts
  server/src/constants.ts
  server/src/user/dto/bind-email.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: size/L

#1426 fix(web): fix drag upload folder
  web/src/components/FileUpload/index.tsx
  web/src/pages/app/storages/mods/UploadButton/index.tsx
Labels: size/M

#1431 feat(cli): support multi folder & path
  cli/src/action/function/index.ts
  cli/src/command/function/index.ts
  cli/src/schema/function.ts
Labels: size/M

#1432 fix(build): fix minio helm custom commands
  build/charts/minio/values.yaml
Labels: size/XS

#1433 fix(server): miss dependence
  server/package-lock.json
  server/package.json
Labels: size/XS
