Repository labring/laf, pull requests merged in 2023-05, with the labels that each got.

#1110 doc: fix the error about H5 call SDK
  docs/guide/client-sdk/index.md
Labels: size/M

#1102 doc: fix docs typos
  docs/.vitepress/theme/custom.css
  docs/guide/function/index.md
  docs/guide/oss/index.md
  docs/guide/website-hosting/index.md
  docs/index.md
  docs/package-lock.json
  docs/package.json
  docs/scripts/check-version.js
Labels: size/M

#1106 ci: modify yarn installation to npm
  .github/workflows/link-pr.yml
Labels: size/XS

#1108 feat(web): add link copy in oss page
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/storages/mods/FileList/index.tsx
  web/src/pages/app/storages/mods/UploadButton/index.tsx
Labels: size/M

#1111 feat(web): hide phone number info
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/home/mods/Empty/index.tsx
  web/src/utils/format.ts
Labels: size/S

#1105 fix(client-sdk): fix bugs in compiling uniapp into WeChat mini programs
  packages/client-sdk/src/cloud.ts
Labels: size/XS

#1109 doc: add web-ide page and VS Code plugin documentation, and adjust the documentation structure
  docs/.vitepress/config.js
  docs/3min/index.md
  docs/diagrams/laf-arch-full.excalidraw
  docs/diagrams/laf-arch-simple.excalidraw
  docs/doc-images/app-list.png
  docs/doc-images/create-laf-app.jpg
  docs/doc-images/index.png
  docs/doc-images/register.png
  docs/doc-images/specification.jpg
  docs/doc-images/web-ide-index.png
  docs/examples/3min-login.md
  docs/examples/alipay-pay.md
  docs/examples/aliyun-sms.md
  docs/examples/github-actions-blog.md
  docs/examples/health-check.md
  docs/examples/polkadot-transaction.md
  docs/examples/send-mail.md
  docs/examples/todo-list.md
  docs/examples/websocket.md
  docs/examples/wechat-notify.md
  docs/examples/wechat-pay.md
  docs/guide/function/env.md
  docs/guide/function/faq.md
  docs/guide/index.md
  docs/guide/laf-assistant/index.md
  docs/guide/web-ide/index.md
  docs/guide/website-hosting/index.md
  docs/screenshots.md
Labels: wip, size/XXL

#1113 feat(web): add function params storage
  web/src/apis/typing.d.ts
  web/src/pages/app/functions/mods/DebugPanel/BodyParamsTab/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/QueryParamsTab/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
Labels: size/M

#1114 doc: modify the default format of the cloud function
  docs/guide/db/add.md
  docs/guide/db/aggregate.md
  docs/guide/function/faq.md
  docs/guide/function/function-param.md
  docs/guide/function/use-function.md
  docs/guide/oss/get-sts.md
  docs/guide/oss/index copy.md
  docs/guide/oss/oss-by-function.md
  docs/guide/oss/upload-by-function.md
  docs/guide/quick-start/login.md
Labels: size/L

#1116 doc: abandon the old environment variable method
  docs/guide/function/env.md
  docs/guide/oss/get-sts.md
  docs/guide/oss/oss-by-function.md
  docs/guide/oss/upload-by-function.md
  docs/guide/web-ide/index.md
Labels: size/M

#1117 chore(deploy): update deploy scripts
  deploy/build/charts/laf-web/templates/NOTES.txt
  deploy/scripts/install-on-linux.sh
Labels: size/XS

#1118 docs(web): change discord link
  web/src/pages/homepage/footer.tsx
  web/src/pages/homepage/joinus.tsx
Labels: size/S

#1112 feat(server): support deployment rolling update
  server/src/instance/instance-task.service.ts
  server/src/instance/instance.service.ts
Labels: size/L

#1119 doc: fix env error
  docs/guide/function/function-param.md
Labels: size/XS

#1123 doc: fix getOne error
  docs/guide/db/find.md
Labels: size/XS

#1126 feat(web): add laf site setting config
  web/src/App.tsx
  web/src/apis/typing.d.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/settings.ts
  web/src/layouts/Header/index.tsx
  web/src/pages/homepage/footer.tsx
  web/src/pages/homepage/navbar.tsx
  web/src/pages/siteSetting.ts
Labels: size/L

#1129 fix(server): cannot restart stopped app
  server/src/application/application.controller.ts
  server/src/instance/instance.service.ts
Labels: size/M

#1127 feat(web): add laf status link
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/CommonIcon/index.ts
  web/src/pages/homepage/footer.tsx
  web/src/pages/homepage/globals.css
  web/src/pages/homepage/navbar.tsx
  web/src/pages/homepage/status.module.scss
  web/src/pages/homepage/status.tsx
Labels: size/L

#1128 fix(web): cannot restart stopped app
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/constants/index.ts
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/globalStore.ts
  web/src/pages/home/mods/List/index.tsx
  web/src/pages/home/mods/StatusBadge/index.tsx
  web/src/pages/homepage/footer.tsx
Labels: size/M

#1124 doc: Update install-on-linux.sh add some install command
  deploy/scripts/install-on-linux.sh
Labels: size/XS

#1133 feat(server): add npm install flags to region; opt instance starting perf
  runtimes/nodejs/init.sh
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/init.ts
  runtimes/nodejs/src/support/cloud-sdk.ts
  runtimes/nodejs/src/support/function-log.ts
  runtimes/nodejs/src/support/token.ts
  runtimes/nodejs/start.sh
  server/prisma/schema.prisma
  server/src/application/application-task.service.ts
  server/src/instance/instance-task.service.ts
  server/src/instance/instance.service.ts
Labels: size/L

#1135 fix(runtime): empty volume mounted error in runtime image
  runtimes/nodejs/init.sh
Labels: size/XS

#1136 chore(cli): modify some default templates
  cli/src/action/function/index.ts
  cli/template/gitignore
Labels: size/XS

#1146 feat: VSCode supports automatic introduction of cloud functions.
  cli/template/tsconfig.json
  docs/guide/laf-assistant/index.md
Labels: size/S

#1131 doc: add depend tips
  docs/guide/function/faq.md
Labels: size/M

#1143 feat: laf-server support i18n (example)
  server/README.md
  server/env.sh
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/function/function.controller.ts
  server/src/generated/i18n.generated.ts
  server/src/i18n/en/function.json
  server/src/i18n/en/subscription.json
  server/src/i18n/zh-CN/function.json
  server/src/i18n/zh-CN/subscription.json
  server/src/i18n/zh/function.json
  server/src/i18n/zh/subscription.json
Labels: size/L

#1147 doc: delete old pic
  README_en.md
Labels: size/S

#1149 fix(server): default request ephemeral-storeage error
  server/src/instance/instance.service.ts
Labels: size/XS

#1158 fix(web): running wouldn't publish code
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
Labels: size/XS

#1152 chore(server): update @lafjs/cloud runtime version
  server/src/runtime-builtin-deps.ts
Labels: size/XS

#1144 feat(web): add signup with invitecode
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/auth/signup/index.tsx
  web/src/pages/home/mods/List/index.tsx
Labels: size/M

#1164 doc: fix wrong format
  docs/guide/function/faq.md
Labels: size/XS

#1169 Design metering
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/billing/billing.controller.ts
  server/src/billing/billing.module.ts
  server/src/billing/billing.service.ts
  server/src/billing/dto/calculate-price.dto.ts
  server/src/billing/entities/resource.ts
  server/src/billing/resource.service.ts
  server/src/database/collection/collection.controller.ts
  server/src/initializer/initializer.service.ts
  server/src/region/entities/resource.ts
  server/src/region/region.controller.ts
  server/src/region/region.module.ts
  server/src/utils/response.ts
Labels: size/L

#1166 refactor(cli): refactor cli structure
  cli/src/action/application/index.ts
  cli/src/action/auth/index.ts
  cli/src/action/dependency/index.ts
  cli/src/action/function/index.ts
  cli/src/action/policy/index.ts
  cli/src/action/storage/index.ts
  cli/src/action/user/index.ts
  cli/src/action/website/index.ts
  cli/src/api/pat.ts
  cli/src/command/auth/index.ts
  cli/src/command/user/index.ts
  cli/src/common/constant.ts
  cli/src/common/hook.ts
  cli/src/common/wait.ts
  cli/src/config/application.ts
  cli/src/config/function.ts
  cli/src/config/secret.ts
  cli/src/config/system.ts
  cli/src/main.ts
  cli/src/schema/app.ts
  cli/src/schema/function.ts
  cli/src/schema/project.ts
  cli/src/schema/user.ts
  cli/src/util/request.ts
  cli/src/util/sys.ts
Labels: size/XL

#1163 feat(web): add function fetch button
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/InputTag/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FetchButton/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/store.ts
Labels: size/L

#1173 feat(web): metering web
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/home/index.tsx
  web/src/pages/home/mods/CreateAppModal/BundleItem/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/L

#1175 fix(web): modal height
  web/public/locales/en/translation.json
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/pages/home/mods/List/BundleInfo.tsx
  web/src/pages/home/mods/List/index.tsx
Labels: size/M

#1174 fix(cli): fix ignore file
  cli/template/gitignore
Labels: size/XS

#1176 feat(cli): add base deploy
  cli/src/action/application/index.ts
  cli/src/action/deploy/index.ts
  cli/src/action/storage/index.ts
  cli/src/action/user/index.ts
  cli/src/api/pat.ts
  cli/src/command/deploy/index.ts
  cli/src/command/storage/index.ts
  cli/src/command/user/index.ts
  cli/src/common/constant.ts
  cli/src/main.ts
  cli/src/schema/app.ts
  cli/src/schema/deploy.ts
  cli/src/schema/function.ts
  cli/src/schema/project.ts
  cli/src/schema/user.ts
  cli/tsconfig.json
Labels: size/L

#1183 feat(server): add invite code feature and billings pagination
  server/src/auth/dto/passwd-signup.dto.ts
  server/src/auth/dto/phone-signin.dto.ts
  server/src/auth/entities/invite-code.ts
  server/src/auth/phone/phone.service.ts
  server/src/auth/user-passwd/user-password.controller.ts
  server/src/auth/user-passwd/user-password.service.ts
  server/src/billing/billing.controller.ts
  server/src/billing/billing.module.ts
  server/src/billing/billing.service.ts
Labels: size/L

#1182 fix(web): fix function template's indentation
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/functionTemplates.ts
Labels: size/L

#1184 fix(web): update app state api & rules add api
  web/.swagger.config.js
  web/src/apis/v1/accounts.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/applications.ts
  web/src/apis/v1/resources.ts
  web/src/components/ChargeButton/index.tsx
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/database/PolicyDataList/index.tsx
  web/src/pages/app/database/PolicyListPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/mods/TriggerModal/index.tsx
  web/src/pages/app/functions/service.ts
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/AppInfoList/InfoDetail/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/setting/PATList/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/app/storages/mods/StorageListPanel/index.tsx
  web/src/pages/globalStore.ts
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/pages/home/mods/List/index.tsx
Labels: size/XL

#1185 refactor(web): api definitions
  web/src/apis/typing.d.ts
  web/src/apis/v1/accounts.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/applications.ts
  web/src/apis/v1/apps.ts
  web/src/apis/v1/auth.ts
  web/src/apis/v1/pat2token.ts
  web/src/apis/v1/pats.ts
  web/src/apis/v1/profile.ts
  web/src/apis/v1/regions.ts
  web/src/apis/v1/resources.ts
  web/src/apis/v1/runtimes.ts
  web/src/apis/v1/settings.ts
  web/src/pages/app/database/service.ts
  web/src/pages/app/setting/AppEnvList/service.ts
  web/src/pages/globalStore.ts
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/L

#1186 Feat definition
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/M

#1188 fix(server): fix server dockerfile error; web merge conflict
  server/Dockerfile
  web/src/pages/app/functions/store.ts
Labels: size/XS

#1189 fix(server): IResponse type def error
  server/build-image.sh
  server/src/account/account.controller.ts
  server/src/utils/interface.ts
  web/package.json
Labels: size/S

#1191 build: fix laf-server image build slowly
  .github/workflows/dockerize-server.yml
  server/.dockerignore
  server/Dockerfile
Labels: size/S

#1192 fix(server): add trial bundle checks in updating application
  server/src/application/application.controller.ts
  server/src/application/application.service.ts
  server/src/billing/dto/calculate-price.dto.ts
Labels: size/M

#1190 feat(cli): add website deploy
  cli/package-lock.json
  cli/package.json
  cli/src/action/deploy/index.ts
  cli/src/schema/deploy.ts
Labels: size/M

#1193 fix(server): update resource price to 0 in initializer
  server/src/application/application.controller.ts
  server/src/initializer/initializer.service.ts
Labels: size/S

#1194 fix(web): pat copy missed
  web/src/pages/app/setting/PATList/index.tsx
Labels: size/XS

#1198 fix(server): creating website report not found error
  runtimes/nodejs-tcb/TODO.md
  server/src/website/website.service.ts
Labels: size/XS

#1197 fix(server): update billings get api; add createdby to billing schema
  server/src/billing/billing-task.service.ts
  server/src/billing/billing.controller.ts
  server/src/billing/billing.service.ts
  server/src/billing/entities/application-billing.ts
Labels: size/L

#1201 fix(server): Fix invitation code signup issue
  server/src/auth/dto/passwd-signup.dto.ts
  server/src/auth/dto/phone-signin.dto.ts
  server/src/auth/phone/phone.service.ts
  server/src/auth/user-passwd/user-password.service.ts
Labels: size/XS

#1202 fix(server): rename limit to pageSize in func log api
  server/src/function/function.service.ts
  server/src/log/log.controller.ts
Labels: size/S

#1195 feat(web): billing page
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/apps.ts
  web/src/apis/v1/billings.ts
  web/src/components/EditableTable/NormalTr/index.tsx
  web/src/components/EditableTable/index.tsx
  web/src/components/Pagination/index.tsx
  web/src/layouts/Header/UserSetting/index.tsx
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/database/service.ts
  web/src/pages/app/logs/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/home/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/utils/getPageInfo.ts
Labels: size/XL

#1203 feat(runtime): support multi-level uri of cloud function
  runtimes/nodejs/env.sh
  runtimes/nodejs/src/handler/router.ts
  runtimes/python/TBD.md
  server/src/account/account.controller.ts
  server/src/function/dto/create-function.dto.ts
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
Labels: size/M

#1204 fix(web): balance value error in cost center page
  server/src/billing/billing.service.ts
  web/src/pages/app/setting/Usage/index.tsx
Labels: size/XS

#1206 fix(web): fix function name regx error
  server/src/function/dto/create-function.dto.ts
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
Labels: size/XS
