Repository labring/laf, pull requests merged in 2023-11, with the labels that each got.

#1618 feat(runtime): refactor log console & enable module cache
  package-lock.json
  package.json
  runtimes/nodejs/README.md
  runtimes/nodejs/package.json
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/handler/invoke.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/storage-server.ts
  runtimes/nodejs/src/support/engine/cache.ts
  runtimes/nodejs/src/support/engine/console.ts
  runtimes/nodejs/src/support/engine/function.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/engine/types.ts
  runtimes/nodejs/src/support/engine/utils.ts
  runtimes/nodejs/src/support/ws.ts
  server/src/gateway/ingress/runtime-ingress.service.ts
Labels: size/L

#1629 fix(web): fix upload file entry 100 items limit
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/FileUpload/index.tsx
  web/src/pages/app/storages/mods/UploadButton/index.tsx
Labels: size/L

#1630 fix(runtime): fix DISABLE_MODULE_CACHE condition error
  runtimes/nodejs/src/support/engine/module.ts
Labels: size/XS

#1621 feat(runtime): add ts lsp server and enhance module require
  runtimes/nodejs/README.md
  runtimes/nodejs/functions/global.d.ts
  runtimes/nodejs/functions/tsconfig.json
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/support/engine/function.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/engine/types.ts
  runtimes/nodejs/src/support/lsp.ts
  server/src/function/dto/create-function.dto.ts
Labels: size/L

#1627 feat(web): add function editor with lsp
  .vscode/settings.json
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/App.css
  web/src/App.tsx
  web/src/components/DateRangePicker/index.css
  web/src/components/EditableTable/EditableTr/index.tsx
  web/src/components/EditableTable/NormalTr/index.tsx
  web/src/components/EditableTable/index.module.scss
  web/src/components/EditableTable/index.tsx
  web/src/components/Editor/CodeViewer.tsx
  web/src/components/Editor/CommonDiffEditor.tsx
  web/src/components/Editor/ENVEditor.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/JSONEditor.tsx
  web/src/components/Editor/JSONViewer.tsx
  web/src/components/Editor/LanguageClient.ts
  web/src/components/Editor/TextModel.tsx
  web/src/components/Editor/globalDefinition.ts
  web/src/components/Editor/theme/index.css
  web/src/components/Editor/theme/index.js
  web/src/components/Editor/theme/laf_editor_dark_theme.json
  web/src/components/Editor/theme/laf_editor_theme.json
  web/src/components/Editor/typesResolve/globals.ts
  web/src/components/Editor/typesResolve/index.ts
  web/src/components/Editor/typesResolve/requestType.ts
  web/src/components/Editor/typesResolve/responseType.ts
  web/src/components/Editor/typesResolve/streamType.ts
  web/src/components/Editor/typesResolve/websocketType.ts
  web/src/components/Editor/userWorker.ts
  web/src/components/IconText/index.module.scss
  web/src/components/SectionList/index.module.scss
  web/src/components/TextButton/index.tsx
  web/src/constants/index.ts
  web/src/hooks/useFunctionCache.ts
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.css
  web/src/pages/app/functions/mods/DeployButton/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.css
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/mods/HeadPanel/index.css
  web/src/pages/app/functions/mods/HeadPanel/index.tsx
  web/src/pages/app/functions/store.ts
  web/src/pages/app/mods/StatusBar/LSPBar/index.tsx
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/app/setting/SysSetting/AppEnvList/index.tsx
  web/src/pages/app/setting/SysSetting/AppEnvList/service.ts
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddEnvironmentsModal.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/vite.config.ts
Labels: size/XXL

#1632 fix(runtime): fix build error
  runtimes/nodejs/src/support/engine/types.ts
Labels: size/XS

#1634 feat(web): add pods logs modal
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/apps.ts
  web/src/pages/app/functions/mods/ConsolePanel/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/store.ts
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/utils/streamFetch.ts
Labels: size/XL

#1631 feat(server): add pod log interface
  server/src/application/application.module.ts
  server/src/application/dto/pod.dto.ts
  server/src/application/pod.controller.ts
  server/src/application/pod.service.ts
  server/src/log/log.controller.ts
Labels: size/L

#1636 fix(web): fix inner html with LogViewer
  web/package-lock.json
  web/package.json
  web/src/App.css
  web/src/components/DateRangePicker/index.css
  web/src/components/IconText/index.module.scss
  web/src/components/SectionList/index.module.scss
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.css
  web/src/pages/app/functions/mods/ConsolePanel/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.css
  web/src/pages/app/functions/mods/HeadPanel/index.css
  web/src/pages/app/mods/StatusBar/LogsModal/index.css
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
  web/src/utils/streamFetch.ts
Labels: size/L

#1637 feat(runtime): beautify runtime log format
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/handler/invoke.ts
  runtimes/nodejs/src/support/engine/console.ts
  runtimes/nodejs/src/support/engine/function.ts
  server/src/gateway/ingress/runtime-ingress.service.ts
Labels: size/L

#1639 fix(web): log viewer line height and fontsize
  web/src/pages/app/mods/StatusBar/LogsModal/index.css
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
Labels: size/XS

#1641 styles(web): fix logs date & adjust logs modal font family
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/ConsolePanel/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/mods/StatusBar/LogsModal/index.css
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
Labels: size/M

#1642 chore: add LOG_DEPTH conf to runtime, beautify log format
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/support/engine/console.ts
  runtimes/nodejs/src/support/logger.ts
Labels: size/M

#1645 fix(web): fix wrap of log amended
  web/src/pages/app/mods/StatusBar/LogsModal/index.scss
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
Labels: size/XS

#1619 feat(exporter): add runtime exporter
  .github/workflows/dockerize-runtime-exporter.yml
  build/charts/laf-server/templates/_helpers.tpl
  build/charts/laf-server/templates/rumtime-exporter.yaml
  build/charts/laf-server/values.yaml
  build/start.sh
  services/runtime-exporter/.dockerignore
  services/runtime-exporter/.gitignore
  services/runtime-exporter/.prettierrc
  services/runtime-exporter/Dockerfile
  services/runtime-exporter/package-lock.json
  services/runtime-exporter/package.json
  services/runtime-exporter/src/config.ts
  services/runtime-exporter/src/handler/get-runtime-metrics.ts
  services/runtime-exporter/src/helper/cluster.service.ts
  services/runtime-exporter/src/index.ts
  services/runtime-exporter/src/logger.ts
  services/runtime-exporter/tsconfig.build.json
  services/runtime-exporter/tsconfig.json
Labels: size/XL

#1628 refactor(server): get metering data of billing from prometheus
  server/package-lock.json
  server/package.json
  server/src/billing/billing-creation-task.service.ts
  server/src/billing/billing.service.ts
  server/src/monitor/monitor.service.ts
Labels: size/M

#1648 refactor(server): refactor billing
  build/charts/laf-server/templates/deployment.yaml
  build/charts/laf-server/values.yaml
  build/start.sh
  deploy/install-on-linux.sh
  server/src/billing/billing-creation-task.service.ts
  server/src/billing/billing.service.ts
  server/src/billing/metering-database.ts
  server/src/constants.ts
Labels: size/L

#1649 refactor(web): handle large header data
  .vscode/settings.json
  web/package-lock.json
  web/package.json
  web/src/pages/app/functions/mods/ConsolePanel/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/utils/handleData.ts
Labels: size/M

#1651 chore(web): refactor log req/resp header
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
Labels: size/XS

#1638 fix(runtime): fix interceptor main func error
  runtimes/nodejs/src/support/engine/function.ts
Labels: size/XS

#1650 chore(server): handle get metering data error
  server/src/billing/billing-creation-task.service.ts
  server/src/billing/billing.service.ts
Labels: size/S

#1655 refactor(log-server): remove old log server
  .github/workflows/dockerize-log-server.yml
  build/charts/laf-server/templates/_helpers.tpl
  build/charts/laf-server/templates/deployment.yaml
  build/charts/laf-server/templates/log-server.yaml
  build/charts/laf-server/values.yaml
  build/start.sh
  server/src/constants.ts
  server/src/function/function.service.ts
  server/src/initializer/initializer.service.ts
  server/src/instance/instance.service.ts
  services/log-server/.dockerignore
  services/log-server/.gitignore
  services/log-server/.prettierrc
  services/log-server/Dockerfile
  services/log-server/commitlint.config.js
  services/log-server/package-lock.json
  services/log-server/package.json
  services/log-server/src/config.ts
  services/log-server/src/db.ts
  services/log-server/src/handler/add-function-log.ts
  services/log-server/src/handler/get-function-log.ts
  services/log-server/src/helper/ensure-collection-exist.ts
  services/log-server/src/helper/verify-appid.ts
  services/log-server/src/index.ts
  services/log-server/src/logger.ts
  services/log-server/tsconfig.json
Labels: size/XL

#1656 chore(server): add labels to ingress resources
  server/src/gateway/ingress/bucket-ingress.service.ts
  server/src/gateway/ingress/runtime-ingress.service.ts
  server/src/gateway/ingress/website-ingress.service.ts
  server/src/instance/instance.service.ts
Labels: size/S

#1661 refactor(web): change old logs position
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/CommonIcon/index.tsx
  web/src/constants/index.ts
  web/src/pages/app/logs/index.tsx
  web/src/pages/app/mods/SideBar/Icons.tsx
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/app/setting/index.tsx
Labels: size/M

#1662 fix(web): fix pages without logs
  web/src/pages/app/index.tsx
Labels: size/XS

#1663 fix(services): Fix metrics data caching issue
  build/charts/laf-server/templates/rumtime-exporter.yaml
  services/runtime-exporter/src/handler/get-runtime-metrics.ts
Labels: size/XS

#1664 fix(services): fix runtime exporter metrics data caching issue
  services/runtime-exporter/src/handler/get-runtime-metrics.ts
Labels: size/XS

#1659 fix(server): fix billing miss on old app
  server/src/application/entities/application.ts
  server/src/billing/billing-creation-task.service.ts
Labels: size/M

#1666 fix(server): fix billing miss on old app
  server/src/application/application.service.ts
  server/src/application/entities/application.ts
  server/src/billing/billing-creation-task.service.ts
Labels: size/S

#1667 chore(server): enhance billing loop when app stop -> start
  server/src/application/application.service.ts
  server/src/application/entities/application.ts
  server/src/instance/instance-task.service.ts
Labels: size/S

#1668 refactor(runtime): refactor the cloud function engine
  packages/cloud-sdk/src/cloud.interface.ts
  runtimes/nodejs/README.md
  runtimes/nodejs/src/handler/invoke.ts
  runtimes/nodejs/src/support/cloud-sdk.ts
  runtimes/nodejs/src/support/engine/cache.ts
  runtimes/nodejs/src/support/engine/executor.ts
  runtimes/nodejs/src/support/engine/function.ts
  runtimes/nodejs/src/support/engine/index.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/engine/types.ts
  runtimes/nodejs/src/support/engine/utils.ts
  runtimes/nodejs/src/support/init-hook.ts
  runtimes/nodejs/src/support/policy.ts
  runtimes/nodejs/src/support/ws.ts
Labels: size/XL

#1671 refactor(server): use record rules to enhance billing performance
  build/charts/laf-server/templates/rumtime-exporter.yaml
  server/src/billing/billing.service.ts
Labels: size/S

#1670 feat(web): cpu and memory monitor support "all" option
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/CommonIcon/index.tsx
  web/src/pages/app/functions/mods/ConsolePanel/index.tsx
  web/src/pages/app/index.tsx
  web/src/pages/app/mods/StatusBar/LogsModal/index.scss
  web/src/pages/app/mods/StatusBar/MonitorBar/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/utils/handleData.ts
Labels: size/L

#1673 fix(server): fix get metering data miss quota
  server/src/billing/billing.service.ts
Labels: size/XS

#1672 fix(web): fix mergeArrays function
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
Labels: size/S

#1675 fix(web): fix padding array with front and end
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
Labels: size/S

#1682 fix(web): fix app monitor longest array
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
Labels: size/M

#1686 chore(server): update default resource request of runtime pod
  server/src/application/application.service.ts
Labels: size/XS

#1684 fix(runtime): object check
  runtimes/nodejs/src/handler/invoke.ts
  runtimes/nodejs/src/support/engine/console.ts
  runtimes/nodejs/src/support/utils.ts
Labels: size/S

#1692 fix(server): add field whitelist for validation
  server/src/application/environment.controller.ts
  server/src/database/dto/create-policy.dto.ts
  server/src/database/dto/create-rule.dto.ts
  server/src/database/dto/update-collection.dto.ts
  server/src/database/dto/update-policy.dto.ts
  server/src/dependency/dependency.controller.ts
  server/src/function-template/dto/create-function-template.dto.ts
  server/src/function-template/dto/use-function-template.dto.ts
  server/src/function/dto/compile-function.dto.ts
  server/src/main.ts
Labels: size/M

#1693 chore: lint the remaining codes
  docs/.eslintignore
  packages/node-modules-utils/.eslintrc
  runtimes/nodejs/src/handler/invoke.ts
  runtimes/nodejs/src/support/utils.ts
Labels: size/S

#1700 chore: update readme wechat link
  README.md
Labels: size/XS

#1689 feat(server): Add a consolidated multi-pod, multi-container log query
  server/README.md
  server/src/application/application.module.ts
  server/src/application/dto/pod.dto.ts
  server/src/application/pod.controller.ts
  server/src/application/pod.service.ts
  server/src/log/log.controller.ts
Labels: size/L

#1691 feat(web): support consolidated multi-pod, multi-container log query
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/apps.ts
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
Labels: size/L

#1702 feat(server): support request-limit ratio conf of runtime resource in region
  server/Dockerfile
  server/package.json
  server/src/application/application.controller.ts
  server/src/application/application.service.ts
  server/src/initializer/initializer.service.ts
  server/src/region/entities/region.ts
Labels: size/M

#1705 chore(build): update github workflows to build images for pr events
  .github/workflows/build-sealos-cluster-image.yml
  .github/workflows/doc-preview.yml
  .github/workflows/dockerize-runtime-exporter.yml
  .github/workflows/dockerize-runtime-nodejs.yml
  .github/workflows/dockerize-server.yml
  .github/workflows/dockerize-web.yml
Labels: size/L

#1706 chore: fix workflow pr check error
  .github/workflows/doc-preview.yml
  .github/workflows/dockerize-runtime-exporter.yml
  .github/workflows/dockerize-runtime-nodejs.yml
  .github/workflows/dockerize-server.yml
  .github/workflows/dockerize-web.yml
  .github/workflows/link-pr.yml
Labels: size/M

#1707 fix(runtime): fix module.exports error; fix logs error while response.chunkedEncoding is true
  runtimes/nodejs/README.md
  runtimes/nodejs/src/handler/invoke.ts
  runtimes/nodejs/src/support/engine/module.ts
Labels: size/M

#1709 fix(runtime): fix process.env hot reload
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/support/cloud-sdk.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/engine/types.ts
Labels: size/S

#1658 feat(runtime): detach custom dependency, support node_module caching
  .vscode/settings.json
  runtimes/nodejs/Dockerfile.init
  runtimes/nodejs/init.sh
  runtimes/nodejs/package.json
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/db.ts
  runtimes/nodejs/src/handler/typings.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/start.sh
  server/README.md
  server/package-lock.json
  server/package.json
  server/src/constants.ts
  server/src/dependency/dependency.service.ts
  server/src/instance/instance.service.ts
  server/src/runtime-builtin-deps.ts
  server/src/storage/bucket.controller.ts
  server/src/storage/bucket.service.ts
  server/src/storage/cloud-bin-bucket.service.ts
  server/src/storage/minio/minio.service.ts
  server/src/storage/storage.module.ts
  server/src/storage/storage.service.ts
Labels: size/L

#1712 feat(runtime): support relative path import of fn
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/engine/types.ts
  server/src/function/dto/create-function.dto.ts
Labels: size/M

#1713 fix(web): function return shows when not undefined & update current function after edit name
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/VersionHistoryPanel/FetchModal/index.tsx
  web/src/pages/app/functions/mods/VersionHistoryPanel/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
Labels: size/M

#1678 doc: sync features with beta 13 updates
  .github/workflows/doc-preview.yml
  docs/.vitepress/config.js
  docs/3min/wechat/MediaPlatform/H5.md
  docs/doc-images/new-logs-1.jpg
  docs/doc-images/old-logs.jpg
  docs/en/3min/wechat/MediaPlatform/H5.md
  docs/en/guide/db/find.md
  docs/en/guide/function/interceptor.md
  docs/guide/client-sdk/index.md
  docs/guide/db/find.md
  docs/guide/function/depend.md
  docs/guide/function/function-sdk.md
  docs/guide/function/interceptor.md
  docs/guide/function/logs.md
  docs/guide/specification/index.md
Labels: size/XL

#1716 doc: delete expired content
  .github/workflows/doc-preview.yml
  docs/guide/web-ide/index.md
Labels: size/S
