Repository labring/laf, pull requests merged in 2023-10, with the labels that each got.

#1561 fix(web): fix function list folder name display
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
Labels: size/XS

#1560 feat(runtime): proxy cloud storage request to minio
  runtimes/nodejs/Dockerfile
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/constants.ts
  runtimes/nodejs/src/handler/router.ts
  runtimes/nodejs/src/handler/typings.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/storage-server.ts
  runtimes/nodejs/src/support/database-change-stream/conf-change-stream.ts
  runtimes/nodejs/src/support/database-change-stream/index.ts
  runtimes/nodejs/src/support/database-change-stream/website-hosting-change-stream.ts
  runtimes/nodejs/src/support/db-change-stream.ts
  runtimes/nodejs/src/support/function-engine/cache.ts
  runtimes/nodejs/src/support/function-engine/console.ts
  runtimes/nodejs/src/support/function-engine/engine.ts
  runtimes/nodejs/src/support/function-engine/require.ts
  runtimes/nodejs/src/support/function-engine/types.ts
Labels: size/L

#1559 feat(gateway): refactor gateway to support ingress
  .vscode/settings.json
  build/Kubefile
  build/charts/apisix/.helmignore
  build/charts/apisix/Chart.lock
  build/charts/apisix/Chart.yaml
  build/charts/apisix/README.md
  build/charts/apisix/README.md.gotmpl
  build/charts/apisix/charts/apisix-dashboard-0.8.0.tgz
  build/charts/apisix/charts/apisix-ingress-controller-0.11.4.tgz
  build/charts/apisix/charts/etcd-8.7.7.tgz
  build/charts/apisix/templates/NOTES.txt
  build/charts/apisix/templates/_helpers.tpl
  build/charts/apisix/templates/_pod.tpl
  build/charts/apisix/templates/clusterrole.yaml
  build/charts/apisix/templates/clusterrolebinding.yaml
  build/charts/apisix/templates/configmap.yaml
  build/charts/apisix/templates/daemonset.yaml
  build/charts/apisix/templates/deployment.yaml
  build/charts/apisix/templates/hpa.yaml
  build/charts/apisix/templates/ingress-admin.yaml
  build/charts/apisix/templates/ingress.yaml
  build/charts/apisix/templates/pdb.yaml
  build/charts/apisix/templates/service-admin.yaml
  build/charts/apisix/templates/service-control-plane.yaml
  build/charts/apisix/templates/service-gateway.yaml
  build/charts/apisix/templates/service-metrics.yaml
  build/charts/apisix/templates/service-monitor.yaml
  build/charts/apisix/templates/serviceaccount.yaml
  build/charts/apisix/values.schema.json
  build/charts/apisix/values.yaml
  build/charts/laf-server/templates/cert-issuer.yaml
  build/charts/laf-server/templates/deployment.yaml
  build/charts/laf-server/templates/ingress.yaml
  build/charts/laf-server/values.yaml
  build/charts/laf-web/templates/ingress.yaml
  build/charts/minio/templates/console-ingress.yaml
  build/charts/minio/templates/ingress.yaml
  build/images/shim/ImageList
  build/start.sh
  deploy/install-on-linux.sh
  e2e/config.ts
  e2e/e2e.sh
  server/src/application/application-task.service.ts
  server/src/application/application.controller.ts
  server/src/constants.ts
  server/src/gateway/apisix-custom-cert.service.ts
  server/src/gateway/apisix.service.ts
  server/src/gateway/bucket-domain-task.service.ts
  server/src/gateway/certificate.service.ts
  server/src/gateway/gateway.module.ts
  server/src/gateway/ingress/bucket-ingress.service.ts
  server/src/gateway/ingress/runtime-ingress.service.ts
  server/src/gateway/ingress/website-ingress.service.ts
  server/src/gateway/runtime-domain-task.service.ts
  server/src/gateway/website-task.service.ts
  server/src/initializer/initializer.service.ts
  server/src/region/cluster/cluster.service.ts
  server/src/region/entities/region.ts
Labels: size/XXL

#1556 chore(build): optimize installation sequence
  build/start.sh
Labels: size/S

#1563 fix(runtime): fix compile error
  runtimes/nodejs/src/support/function-engine/types.ts
Labels: size/XS

#1564 fix(server): fix nest deps missing
  server/src/gateway/gateway.module.ts
Labels: size/XS

#1565 fix(gateway): fix cors headers conf of runtime; fix ingress nginx installation
  build/charts/laf-server/templates/deployment.yaml
  build/charts/laf-server/values.yaml
  build/charts/laf-web/templates/ingress.yaml
  build/start.sh
  deploy/install-on-linux.sh
  server/src/gateway/ingress/runtime-ingress.service.ts
Labels: size/S

#1566 chore(deploy): fix ingress-nginx image name typo
  deploy/install-on-linux.sh
Labels: size/XS

#1568 fix(server) solving function template sorting problems
  server/src/function-template/function-template.service.ts
Labels: size/XS

#1569 feat(server): add tls config for ingress gateway
  build/charts/laf-server/templates/deployment.yaml
  build/charts/laf-server/values.yaml
  build/start.sh
  server/src/constants.ts
  server/src/gateway/ingress/runtime-ingress.service.ts
  server/src/gateway/ingress/website-ingress.service.ts
  server/src/gateway/runtime-domain.service.ts
  server/src/gateway/website-task.service.ts
  server/src/initializer/initializer.service.ts
Labels: size/M

#1570 chore(web): add sentry
  .github/workflows/dockerize-web.yml
  web/package-lock.json
  web/package.json
  web/pnpm-lock.yaml
  web/src/App.tsx
  web/src/main.tsx
  web/src/pages/globalStore.ts
  web/vite.config.ts
Labels: size/XXL

#1571 chore(ci): set ci getsentry working directory
  .github/workflows/dockerize-web.yml
Labels: size/XS

#1558 feat: optimize ctx data definition
  web/src/components/Editor/typesResolve/globals.ts
Labels: size/XS

#1575 doc: fix Cloud function introduction document path error
  docs/guide/function/function-sdk.md
Labels: size/XS

#1576 doc: optimizing Cloud Function naming document
  docs/guide/function/index.md
Labels: size/XS

#1573 doc: added a tips for appid in cloud storage
  docs/guide/oss/oss-by-function.md
Labels: size/XS

#1572 doc: add cloud sdk attribute introduction
  docs/guide/function/function-sdk.md
Labels: size/S

#1574 doc: fix error about ctx.env
  docs/guide/function/use-function.md
Labels: size/XS

#1543 feat(web): support github login
  web/public/homepage/p2.png
  web/public/homepage/p3.png
  web/public/homepage/p5.png
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/App.tsx
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/auth.ts
  web/src/constants/index.ts
  web/src/layouts/Basic/index.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/index.tsx
  web/src/pages/auth/bind/BindGitHub/index.tsx
  web/src/pages/auth/service.ts
  web/src/pages/auth/signin/index.tsx
  web/src/pages/auth/signin/mods/LoginByPasswordPanel/index.tsx
  web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
  web/src/pages/auth/signup/index.tsx
  web/src/pages/auth/store.ts
  web/src/pages/auth/test.svg
  web/src/routes/index.tsx
  web/tailwind.config.cjs
Labels: size/XL

#1542 feat(server): support github login
  server/package-lock.json
  server/package.json
  server/src/authentication/authentication.module.ts
  server/src/authentication/authentication.service.ts
  server/src/authentication/dto/github-bind.dto.ts
  server/src/authentication/dto/github-jump-login.dto.ts
  server/src/authentication/dto/github-signin.dto.ts
  server/src/authentication/github/github.controller.ts
  server/src/authentication/github/github.service.ts
  server/src/constants.ts
  server/src/user/entities/user.ts
  server/src/user/user.service.ts
Labels: size/L

#1577 feat(server): runtime add sealos manager labels
  server/src/instance/instance.service.ts
Labels: size/S

#1578 fix(server): fix app restart not reapply service
  server/src/instance/instance.service.ts
Labels: size/M

#1580 fix(web): fix sign up navigate & storage display
  web/src/components/FileTypeIcon/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
  web/src/pages/app/storages/mods/FileList/index.tsx
  web/src/pages/auth/signin/index.tsx
  web/src/pages/auth/signup/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/L

#1583 fix(server): fixed runtime labels
  server/src/instance/instance.service.ts
Labels: size/XS

#1584 chore: remove custom storage class, use default sc;
  build/charts/laf-server/templates/cert-issuer.yaml
  build/charts/minio/values.yaml
  build/charts/mongodb/templates/storage.yaml
  build/charts/mongodb/values.yaml
  deploy/install-on-linux.sh
  server/src/gateway/ingress/bucket-ingress.service.ts
Labels: size/M

#1585 fix(server) fix runtime deployment labels
  server/src/instance/instance.service.ts
Labels: size/XS

#1587 fix(web): fix sentry allowlist
  web/src/main.tsx
Labels: size/XS

#1589 doc: Instructions for modifying cloud function logs
  docs/guide/function/logs.md
Labels: size/XS

#1591 feat(cli): improve the cli interface
  cli/template/global.d.ts
Labels: size/S

#1592 fix(runtime): fix db stream initialize
  runtimes/nodejs/src/handler/debug-func.ts
  runtimes/nodejs/src/handler/invoke-func.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/storage-server.ts
  runtimes/nodejs/src/support/database-change-stream/conf-change-stream.ts
  runtimes/nodejs/src/support/database-change-stream/index.ts
  runtimes/nodejs/src/support/database-change-stream/website-hosting-change-stream.ts
  runtimes/nodejs/src/support/function-engine/types.ts
  web/src/components/Editor/typesResolve/globals.ts
Labels: size/M

#1581 refactor(web): cloud storage use ak/sk instead of sts
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/hooks/useAwsS3.ts
  web/src/pages/app/setting/SysSetting/AppEnvList/index.tsx
  web/src/pages/app/storages/mods/CreateBucketModal/index.tsx
Labels: size/M

#1594 fix(web): remove storage.credential
  web/src/pages/app/storages/store.ts
Labels: size/XS

#1590 feat(runtime): refactor function engine
  runtimes/nodejs/src/handler/debug-func.ts
  runtimes/nodejs/src/handler/invoke-func.ts
  runtimes/nodejs/src/handler/invoke.ts
  runtimes/nodejs/src/handler/router.ts
  runtimes/nodejs/src/handler/typings.ts
  runtimes/nodejs/src/support/cloud-sdk.ts
  runtimes/nodejs/src/support/database-change-stream/index.ts
  runtimes/nodejs/src/support/engine/cache.ts
  runtimes/nodejs/src/support/engine/console.ts
  runtimes/nodejs/src/support/engine/function.ts
  runtimes/nodejs/src/support/engine/index.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/engine/types.ts
  runtimes/nodejs/src/support/engine/utils.ts
  runtimes/nodejs/src/support/function-engine/cache.ts
  runtimes/nodejs/src/support/function-engine/engine.ts
  runtimes/nodejs/src/support/function-engine/function.ts
  runtimes/nodejs/src/support/function-engine/require.ts
  runtimes/nodejs/src/support/function-engine/vm.ts
  runtimes/nodejs/src/support/init-hook.ts
  runtimes/nodejs/src/support/policy.ts
  runtimes/nodejs/src/support/ws.ts
Labels: size/XXL

#1595 chore(server): remove minio version control
  server/src/storage/minio/minio.service.ts
Labels: size/S

#1597 fix(runtime): fix update function not effective
  runtimes/nodejs/src/support/engine/cache.ts
  runtimes/nodejs/src/support/engine/module.ts
Labels: size/XS

#1601 chore(ci): update dockerize-web.yml
  .github/workflows/dockerize-web.yml
Labels: size/XS

#1602 feat(runtime): support default function
  runtimes/nodejs/src/handler/invoke.ts
Labels: size/S

#1603 fix(runtime): enable cors in runtime; disable cors in gateway ingress
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/storage-server.ts
  server/src/gateway/ingress/bucket-ingress.service.ts
  server/src/gateway/ingress/runtime-ingress.service.ts
  server/src/gateway/ingress/website-ingress.service.ts
Labels: size/M

#1604 fix(runtime): default close module cache
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/support/engine/module.ts
Labels: size/XS

#1605 chore(build): change prometheus url
  build/start.sh
Labels: size/XS

#1606 fix(web): fix edit bucket name display
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/storages/mods/CreateBucketModal/index.tsx
Labels: size/M

#1610 fix(cli): fix update func bug
  cli/src/action/function/index.ts
  cli/src/api/v1/data-contracts.ts
Labels: size/XS

#1609 fix(cli): storage server api changed for cli
  cli/src/action/application/index.ts
Labels: size/XS

#1612 refactor(gateway): refactor logics of ingress deletion
  runtimes/nodejs/start.sh
  server/src/gateway/ingress/bucket-ingress.service.ts
  server/src/gateway/runtime-domain-task.service.ts
  server/src/gateway/website-task.service.ts
  server/src/instance/instance-task.service.ts
Labels: size/M

#1613 fix(server): set deleting phase when deleting app
  server/src/gateway/runtime-domain.service.ts
  server/src/website/website.service.ts
Labels: size/S

#1615 feat: Cors added Access-Control-Max-Age
  runtimes/nodejs/src/index.ts
Labels: size/XS

#1623 fix(server): update logic of cronjob deletion
  server/src/constants.ts
  server/src/instance/instance-task.service.ts
  server/src/instance/instance.module.ts
  server/src/trigger/trigger-task.service.ts
Labels: size/M

#1611 feat(web&sdk): add index manage
  packages/database-proxy/src/accessor/accessor.ts
  packages/database-proxy/src/accessor/mongo.ts
  packages/database-proxy/src/types.ts
  packages/database-ql/src/collection.ts
  packages/database-ql/src/constant.ts
  packages/database-ql/src/document.ts
  packages/database-ql/src/interface.ts
  packages/database-ql/src/query.ts
  packages/database-ql/src/result-types.ts
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/PopConfirm/index.tsx
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/database/mods/AddIndexModal/index.tsx
  web/src/pages/app/database/mods/IndexModal/index.tsx
  web/src/pages/app/database/service.ts
Labels: size/XXL

#1624 chore: remove husky from laf-web
  web/.husky/pre-commit
  web/package-lock.json
  web/package.json
Labels: size/XS

#1626 fix(web): fix add index bug
  web/src/pages/app/database/mods/AddIndexModal/index.tsx
  web/src/pages/app/database/mods/IndexModal/index.tsx
  web/src/pages/app/database/service.ts
Labels: size/S

#1622 feat(web): footer add 'about us' page
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/constants/index.ts
  web/src/pages/homepage/footer.tsx
Labels: size/S
