Repository labring/laf, pull requests merged in 2023-06, with the labels that each got.

#1207 fix(web): app env & price show
  web/src/pages/app/database/service.ts
  web/src/pages/app/setting/AppEnvList/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/utils/format.ts
Labels: size/M

#1209 fix(web): Remove billingQuery from useEffect dependencies
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/XS

#1214 refactor(web): price free show
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/S

#1179 fix(web): adjust editor tips being obscured and some other style problems
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/mods/SideBar/index.module.scss
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/AppInfoList/InfoDetail/index.tsx
Labels: size/M

#1216 fix(server): fix billing task concurrency overflow
  deploy/build/charts/laf-server/templates/metering.yaml
  server/src/billing/billing-task.service.ts
Labels: size/S

#1217 fix(web): fix fetch button zh name and width
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/DeployButton/index.tsx
  web/src/pages/app/functions/mods/FetchButton/index.tsx
Labels: size/S

#1210 feat(server): support website history
  deploy/build/charts/apisix/values.yaml
  server/src/gateway/apisix.service.ts
  server/src/gateway/website-task.service.ts
Labels: size/S

#1220 chore(deploy): fix deploy scripts path error
  deploy/README.md
  deploy/install-on-linux.sh
  deploy/install-on-mac.sh
  e2e/e2e.sh
Labels: size/S

#1223 feat(web): update laf ai request url
  web/src/components/ChargeButton/index.tsx
  web/src/constants/index.ts
  web/src/pages/app/functions/mods/AIChatPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
Labels: size/S

#1226 refactor(server): refactor auth api(profile/pat)
  cli/src/api/pat.ts
  cli/src/api/v1/authentication.ts
  server/src/account/account.controller.ts
  server/src/account/account.service.ts
  server/src/account/entities/account-transaction.ts
  server/src/account/entities/payment-channel.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/application/application.controller.ts
  server/src/application/environment.controller.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/authentication/application.auth.guard.ts
  server/src/authentication/authentication.controller.ts
  server/src/authentication/authentication.module.ts
  server/src/authentication/authentication.service.ts
  server/src/authentication/dto/bind-phone.dto.ts
  server/src/authentication/dto/bind-username.dto.ts
  server/src/authentication/dto/passwd-check.dto.ts
  server/src/authentication/dto/passwd-reset.dto.ts
  server/src/authentication/dto/passwd-signin.dto.ts
  server/src/authentication/dto/passwd-signup.dto.ts
  server/src/authentication/dto/pat2token.dto.ts
  server/src/authentication/dto/phone-signin.dto.ts
  server/src/authentication/dto/send-phone-code.dto.ts
  server/src/authentication/entities/auth-provider.ts
  server/src/authentication/entities/invite-code.ts
  server/src/authentication/entities/sms-verify-code.ts
  server/src/authentication/entities/types.ts
  server/src/authentication/jwt.auth.guard.ts
  server/src/authentication/jwt.strategy.ts
  server/src/authentication/phone/phone.controller.ts
  server/src/authentication/phone/phone.service.ts
  server/src/authentication/phone/sms.service.ts
  server/src/authentication/user-passwd/user-password.controller.ts
  server/src/authentication/user-passwd/user-password.service.ts
  server/src/billing/billing.controller.ts
  server/src/database/collection/collection.controller.ts
  server/src/database/database.controller.ts
  server/src/database/policy/policy-rule.controller.ts
  server/src/database/policy/policy.controller.ts
  server/src/dependency/dependency.controller.ts
  server/src/function/function.controller.ts
  server/src/initializer/initializer.service.ts
  server/src/log/log.controller.ts
  server/src/setting/entities/setting.ts
  server/src/setting/setting.controller.ts
  server/src/setting/setting.service.ts
  server/src/storage/bucket.controller.ts
  server/src/trigger/trigger.controller.ts
  server/src/user/pat.controller.ts
  server/src/website/website.controller.ts
  web/src/apis/v1/pat2token.ts
Labels: size/L

#1227 fix(web): fix /v1/profile api url missing
  cli/src/api/v1/authentication.ts
  web/src/apis/v1/profile.ts
Labels: size/XS

#1228 feat(runtime): add chatgpt package builtin runtime
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  server/src/runtime-builtin-deps.ts
Labels: size/S

#1232 chore: upgrade apisix helm version
  build/charts/apisix/Chart.lock
  build/charts/apisix/Chart.yaml
  build/charts/apisix/README.md
  build/charts/apisix/README.md.gotmpl
  build/charts/apisix/charts/apisix-dashboard-0.8.0.tgz
  build/charts/apisix/charts/apisix-dashboard/.helmignore
  build/charts/apisix/charts/apisix-dashboard/Chart.yaml
  build/charts/apisix/charts/apisix-dashboard/README.md
  build/charts/apisix/charts/apisix-dashboard/templates/NOTES.txt
  build/charts/apisix/charts/apisix-dashboard/templates/_helpers.tpl
  build/charts/apisix/charts/apisix-dashboard/templates/configmap.yaml
  build/charts/apisix/charts/apisix-dashboard/templates/deployment.yaml
  build/charts/apisix/charts/apisix-dashboard/templates/hpa.yaml
  build/charts/apisix/charts/apisix-dashboard/templates/serviceaccount.yaml
  build/charts/apisix/charts/apisix-dashboard/templates/tests/test-connection.yaml
  build/charts/apisix/charts/apisix-dashboard/values.yaml
  build/charts/apisix/charts/apisix-ingress-controller-0.11.4.tgz
  build/charts/apisix/charts/apisix-ingress-controller/.helmignore
  build/charts/apisix/charts/apisix-ingress-controller/Chart.yaml
  build/charts/apisix/charts/apisix-ingress-controller/README.md
  build/charts/apisix/charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml
  build/charts/apisix/charts/apisix-ingress-controller/templates/NOTES.txt
  build/charts/apisix/charts/apisix-ingress-controller/templates/_helpers.tpl
  build/charts/apisix/charts/apisix-ingress-controller/templates/configmap.yaml
  build/charts/apisix/charts/apisix-ingress-controller/templates/deployment.yaml
  build/charts/apisix/charts/apisix-ingress-controller/templates/hpa.yaml
  build/charts/apisix/charts/apisix-ingress-controller/templates/rbac.yaml
  build/charts/apisix/charts/apisix-ingress-controller/templates/service.yaml
  build/charts/apisix/charts/apisix-ingress-controller/templates/servicemonitor.yaml
  build/charts/apisix/charts/apisix-ingress-controller/values.yaml
  build/charts/apisix/charts/etcd-8.7.7.tgz
  build/charts/apisix/charts/etcd/.helmignore
  build/charts/apisix/charts/etcd/Chart.yaml
  build/charts/apisix/charts/etcd/README.md
  build/charts/apisix/charts/etcd/templates/NOTES.txt
  build/charts/apisix/charts/etcd/templates/_helpers.tpl
  build/charts/apisix/charts/etcd/templates/service.yaml
  build/charts/apisix/charts/etcd/templates/serviceaccount.yaml
  build/charts/apisix/charts/etcd/templates/statefulset.yaml
  build/charts/apisix/charts/etcd/templates/storage.yaml
  build/charts/apisix/charts/etcd/templates/tests/test-connection.yaml
  build/charts/apisix/charts/etcd/values.yaml
  build/charts/apisix/templates/_helpers.tpl
  build/charts/apisix/templates/_pod.tpl
  build/charts/apisix/templates/configmap.yaml
  build/charts/apisix/templates/hpa.yaml
  build/charts/apisix/templates/ingress-admin.yaml
  build/charts/apisix/templates/ingress.yaml
  build/charts/apisix/templates/service-admin.yaml
  build/charts/apisix/templates/service-control-plane.yaml
  build/charts/apisix/templates/service-gateway.yaml
  build/charts/apisix/templates/service-metrics.yaml
  build/charts/apisix/templates/service-monitor.yaml
  build/charts/apisix/values.schema.json
  build/charts/apisix/values.yaml
  build/start.sh
Labels: size/XXL

#1215 doc: add documents that accesss AI
  docs/.vitepress/config.js
  docs/3min/chatgpt/index.md
  docs/3min/claude/index.md
  docs/3min/midjourney/index.md
  docs/doc-images/SALAI_TOKEN.jpg
  docs/doc-images/mj-id.png
  docs/doc-images/slack-connect-create-1.jpg
  docs/doc-images/slack-connect-create.jpg
  docs/doc-images/slack-connect.jpg
  docs/doc-images/slack-create-app-bot.jpg
  docs/doc-images/slack-create-app.jpg
  docs/doc-images/slack-install-bot.jpg
  docs/guide/function/faq.md
  docs/guide/oss/oss-by-function.md
Labels: size/XL

#1234 chore: update apisix plugins version
  build/charts/apisix/values.yaml
Labels: size/XS

#1235 feat(cli): add error prompt & opt init project
  cli/src/action/application/index.ts
  cli/src/action/function/index.ts
  cli/src/common/constant.ts
  cli/src/schema/function.ts
  cli/src/util/request.ts
Labels: size/M

#1236 fix(server): fix billing task perf problem
  server/src/billing/billing-task.service.ts
Labels: size/S

#1237 fix(server): improve billing task concurrency
  server/src/billing/billing-task.service.ts
Labels: size/S

#1238 chore(deploy): fix deploy scripts PROJECT_ROOT error
  deploy/install-on-mac.sh
Labels: size/XS

#1233 feat(web): opt function editor ui
  web/src/App.css
  web/src/components/CommonIcon/index.tsx
  web/src/components/Content/index.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/FileTypeIcon/index.tsx
  web/src/components/Grid/index.tsx
  web/src/components/Panel/Header.tsx
  web/src/components/Panel/index.module.scss
  web/src/components/Panel/index.tsx
  web/src/components/Resize/index.tsx
  web/src/components/SectionList/index.module.scss
  web/src/components/SectionList/index.tsx
  web/src/constants/index.ts
  web/src/hooks/useResizable.ts
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/functions/mods/ConsolePanel/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/app/functions/mods/DeployButton/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FetchButton/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/logs/index.tsx
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/app/setting/AppInfoList/InfoDetail/index.tsx
  web/src/pages/app/storages/mods/FileList/index.tsx
  web/src/pages/app/storages/mods/StorageListPanel/index.tsx
  web/src/pages/customSetting.ts
  web/src/pages/home/mods/StatusBadge/index.module.scss
Labels: size/L

#1239 fix(web): tabheight
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
Labels: size/XS

#1241 feat(cli): support specify code directory
  cli/src/action/application/index.ts
  cli/src/action/dependency/index.ts
  cli/src/action/function/index.ts
  cli/src/action/policy/index.ts
  cli/src/schema/function.ts
  cli/src/util/sys.ts
Labels: size/M

#1249 refactor(server): refactor billing task
  server/src/billing/billing-creation-task.service.ts
  server/src/billing/billing-payment-task.service.ts
  server/src/billing/billing.module.ts
  server/src/constants.ts
  server/src/main.ts
Labels: size/L

#1251 fix(cli): fix remote url end with /
  cli/src/action/user/index.ts
  cli/src/util/request.ts
Labels: size/XS

#1242 doc: add cli switch user method
  docs/guide/cli/index.md
Labels: size/S

#1253 fix(server): opt billing task schedular cron
  server/src/billing/billing-creation-task.service.ts
  server/src/billing/billing-payment-task.service.ts
  server/src/billing/billing.controller.ts
Labels: size/M

#1252 ci: repair push laf doc
  .github/workflows/deploy-doc.yml
Labels: size/XS

#1255 fix(server): billing task exit abnormally
  server/build-image.sh
  server/src/billing/billing-creation-task.service.ts
  server/src/billing/billing-payment-task.service.ts
Labels: size/L

#1257 fix(web): balance recharge
  web/src/components/ChargeButton/index.tsx
Labels: size/S

#1263 feat(web): add recharge bonus & autoscaling
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/apis/v1/accounts.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/auth.ts
  web/src/components/ChargeButton/index.tsx
  web/src/pages/app/setting/Usage/index.tsx
  web/src/pages/home/mods/CreateAppModal/BundleItem/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/XL

#1264 feat(web): add function template
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/function-templates.ts
  web/src/components/CommonIcon/index.tsx
  web/src/components/FileTypeIcon/index.tsx
  web/src/components/InputTag/index.tsx
  web/src/layouts/Basic.tsx
  web/src/layouts/Header/UserSetting/index.tsx
  web/src/layouts/Header/index.tsx
  web/src/layouts/Template.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/FunctionTemplate/index.tsx
  web/src/pages/app/functions/service.ts
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddDependenceModal.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddEnvironmentsModal.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddFunctionModal.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/index.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/functionTemplate/Mods/PaginationBar/index.tsx
  web/src/pages/functionTemplate/Mods/SideBar/index.module.scss
  web/src/pages/functionTemplate/Mods/TemplateInfo/SponsorModal/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateList/index.tsx
  web/src/pages/functionTemplate/Mods/UseTemplateModal/index.tsx
  web/src/pages/functionTemplate/funcTemplateItem/index.tsx
  web/src/pages/functionTemplate/index.tsx
  web/src/pages/functionTemplate/service.ts
  web/src/pages/homepage/language.tsx
  web/src/pages/homepage/navbar.tsx
  web/src/routes/index.tsx
  web/tailwind.config.cjs
Labels: size/XXL

#1250 feat(server): autoscaling for application
  runtimes/nodejs/package-lock.json
  server/package-lock.json
  server/package.json
  server/src/application/application.controller.ts
  server/src/application/application.service.ts
  server/src/application/dto/create-autoscaling.dto.ts
  server/src/application/dto/update-application.dto.ts
  server/src/application/entities/application-bundle.ts
  server/src/application/entities/application-configuration.ts
  server/src/instance/instance.service.ts
  server/src/region/cluster/cluster.service.ts
Labels: size/L

#1261 feat(server): support charge reward
  server/src/account/account.controller.ts
  server/src/account/account.service.ts
  server/src/account/entities/account-charge-reward.ts
  server/src/account/entities/account-transaction.ts
Labels: size/M

#1265 fix(web): hide template
  web/src/layouts/Header/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
Labels: size/M

#1269 fix(server): fix charge reward calculation error
  server/src/account/account.controller.ts
Labels: size/XS

#1270 fix(cli): fix function exec error
  cli/src/action/application/index.ts
  cli/src/action/function/index.ts
  cli/src/common/hook.ts
  cli/src/schema/app.ts
Labels: size/S

#1271 fix(cli): opt func pull command
  cli/src/action/application/index.ts
  cli/src/action/function/index.ts
  cli/src/command/function/index.ts
Labels: size/M

#1273 fix(web): fix typo
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/XS

#1274 fix(web): fix recharge display & modal open
  web/src/components/ChargeButton/index.tsx
Labels: size/XS

#1275 fix(server): create hpa when hpa is not found
  server/src/instance/instance.service.ts
Labels: size/S

#1276 fix(runtime): add mongodb stream reconnect
  runtimes/nodejs/src/support/db-change-stream.ts
  runtimes/nodejs/src/support/function-engine/cache.ts
Labels: size/S

#1278 chore(web): fix typo in recharge bonus dlg
  server/src/instance/instance.service.ts
  web/src/components/ChargeButton/index.tsx
Labels: size/XS

#1283 feat(server): support cloud function history
  server/src/function/entities/cloud-function-history.ts
  server/src/function/function.controller.ts
  server/src/function/function.service.ts
Labels: size/L

#1285 doc: fix a small mistake
  docs/guide/function/faq.md
Labels: size/XS

#1286 doc: fix case problem
  docs/.vitepress/config.js
Labels: size/XS

#1287 doc: del invalid image links
  README.md
Labels: size/XS

#1288 doc: del invalid image links en
  README_en.md
Labels: size/XS

#1290 fix(server): add sort filter to resource bundle & options
  server/src/billing/resource.service.ts
Labels: size/XS

#1291 doc: fix syntax error on jwt token
  docs/guide/function/faq.md
Labels: size/XS

#1259 feat(server): implements cloud function template & templates marketplace
  build/charts/laf-server/templates/metering.yaml
  server/src/app.module.ts
  server/src/application/application.module.ts
  server/src/dependency/dependency.module.ts
  server/src/dependency/dependency.service.ts
  server/src/function-template/dto/create-function-template.dto.ts
  server/src/function-template/dto/update-function-template.dto.ts
  server/src/function-template/dto/use-function-template.dto.ts
  server/src/function-template/entities/function-template.ts
  server/src/function-template/entities/swagger-help.ts
  server/src/function-template/function-template.controller.ts
  server/src/function-template/function-template.module.ts
  server/src/function-template/function-template.service.ts
  server/tsconfig.json
Labels: size/XXL

#1302 feat(web):add pagination for storage file list
  web/src/pages/app/storages/mods/FileList/index.tsx
Labels: size/L

#1296 fix(web): change ui & add infomation display
  .vscode/settings.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/CommonIcon/index.tsx
  web/src/layouts/Basic.tsx
  web/src/layouts/Header/index.tsx
  web/src/layouts/Template.tsx
  web/src/pages/app/functions/mods/FunctionPanel/FunctionTemplate/index.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddFunctionModal.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/index.tsx
  web/src/pages/functionTemplate/Mods/FunctionPopover/index.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
  web/src/pages/functionTemplate/Mods/UseTemplateModal/index.tsx
  web/src/pages/functionTemplate/funcTemplateItem/index.tsx
  web/src/pages/functionTemplate/index.tsx
  web/src/utils/format.ts
  web/tailwind.config.cjs
Labels: size/XL

#1297 doc: mongo native writing to await mode
  docs/guide/db/add.md
Labels: size/XS

#1300 doc: change the LAF API login step in actions
  docs/guide/website-hosting/index.md
Labels: size/XS

#1306 fix(runtime): update alipay deps
  server/src/runtime-builtin-deps.ts
Labels: size/XS

#1309 doc: change the default url
  README.md
Labels: size/XS

#1295 fix(client-sdk): fix #1282 add polyfill for globalThis
  packages/client-sdk/src/index.ts
Labels: size/S

#1305 fix(web): fix navbar github stars & change bundle billing query
  web/src/layouts/Header/index.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddDependenceModal.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/index.tsx
  web/src/pages/functionTemplate/Mods/FunctionPopover/index.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateList/index.tsx
  web/src/pages/functionTemplate/funcTemplateItem/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/pages/homepage/navbar.tsx
Labels: size/L

#1314 fix(runtime): remove alipay-sdk from runtime
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  server/src/runtime-builtin-deps.ts
Labels: size/XS

#1312 build(main): add sync image for docker.io/labring
  .github/workflows/build-sealos-cluster-image.yml
Labels: size/S

#1317 build(main): add sync image for docker.io/labring
  .github/workflows/build-sealos-cluster-image.yml
Labels: size/XS

#1318 build(main): add sync image for docker.io/labring
  .github/workflows/build-sealos-cluster-image.yml
Labels: size/XS

#1315 feat(web): support checking dep detail by jumping to `npmjs`
  web/src/components/ConfirmButton/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
Labels: size/M

#1311 feat(web): support pwa
  web/package-lock.json
  web/package.json
  web/public/apple-touch-icon.png
  web/public/masked-icon.png
  web/public/pwa-192x192.png
  web/public/pwa-512x512.png
  web/public/pwa-64x64.png
  web/public/robots.txt
  web/vite.config.ts
Labels: size/M

#1319 build(main): add bot for laf
  .github/gh-bot.yml
Labels: size/M

#1320 fix(web):fix body params storage
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
Labels: size/XS

#1321 feat(server): add `message ` field for AccountChargeReward
  server/src/account/entities/account-charge-reward.ts
Labels: size/XS

#1322 doc: update Readme
  README.md
Labels: size/L

#1323 feat(web): add recommend template & change ui
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/App.css
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/apps.ts
  web/src/apis/v1/function-templates.ts
  web/src/assets/login_bg.svg
  web/src/layouts/Header/index.tsx
  web/src/layouts/Template.tsx
  web/src/pages/app/functions/mods/ConsolePanel/index.tsx
  web/src/pages/app/functions/mods/DeployButton/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/FunctionTemplate/index.tsx
  web/src/pages/app/functions/service.ts
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddFunctionModal.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/index.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateCard/TemplateCard.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/UseTemplate.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
  web/src/pages/functionTemplate/Mods/TemplatePopover/TemplatePopover.tsx
  web/src/pages/functionTemplate/Mods/UseTemplateModal/index.tsx
  web/src/pages/functionTemplate/funcTemplateItem/TemplateFunctionInfo.tsx
  web/src/pages/functionTemplate/funcTemplateItem/index.tsx
  web/src/pages/functionTemplate/index.tsx
  web/src/pages/functionTemplate/service.ts
  web/src/routes/index.tsx
  web/src/utils/format.ts
Labels: size/XXL

#1324 fix(web): reset package list when reopen modal && `Restarting` -> `Starting` for app stopped
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
Labels: size/M

#1327 fix(server): sort resource options by created time
  server/src/billing/resource.service.ts
Labels: size/XS

#1328 fix(web): fix search query hooks
  web/src/pages/functionTemplate/index.tsx
Labels: size/S

#1325 feat(client-sdk): support taro request
  packages/client-sdk/src/cloud.ts
  packages/client-sdk/src/request/request-taro.ts
  packages/client-sdk/src/types.ts
Labels: size/M

#1329 fix(web): fix ignore case & use template
  web/src/components/ConfirmButton/index.tsx
  web/src/pages/functionTemplate/FuncTemplateItem/TemplateFunctionInfo.tsx
  web/src/pages/functionTemplate/FuncTemplateItem/index.tsx
Labels: size/L

#1316 fix(server): add recommended function templates and limits for function templates
  server/.gitignore
  server/src/function-template/dto/create-function-template.dto.ts
  server/src/function-template/dto/update-function-template.dto.ts
  server/src/function-template/function-template.controller.ts
  server/src/function-template/function-template.service.ts
Labels: size/L

#1330 fix(web): remove casing error direction
  web/src/pages/functionTemplate/funcTemplateItem/TemplateFunctionInfo.tsx
  web/src/pages/functionTemplate/funcTemplateItem/index.tsx
Labels: size/L

#1331 fix(web): fix navigate & func delete & title overflow
  web/src/pages/functionTemplate/FuncTemplateItem/index.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateCard/TemplateCard.tsx
  web/src/pages/functionTemplate/index.tsx
Labels: size/M

#1333 fix(server): add limits for function templates
  server/src/function-template/dto/create-function-template.dto.ts
  server/src/function-template/dto/update-function-template.dto.ts
Labels: size/XS

#1334 fix(server): don't add history when debug function
  server/src/function/function.service.ts
Labels: size/XS

#1335 fix(web): fix function template popover
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/App.css
  web/src/layouts/Template.tsx
  web/src/pages/app/functions/mods/FunctionPanel/FunctionTemplate/index.tsx
  web/src/pages/functionTemplate/CreateFuncTemplate/index.tsx
  web/src/pages/functionTemplate/FuncTemplateItem/TemplateFunctionInfo.tsx
  web/src/pages/functionTemplate/FuncTemplateItem/index.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/functionTemplate/Mods/PaginationBar/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateCard/TemplateCard.tsx
  web/src/pages/functionTemplate/Mods/TemplatePopover/TemplatePopover.tsx
  web/src/pages/functionTemplate/Mods/UseTemplateModal/index.tsx
  web/src/pages/functionTemplate/index.tsx
Labels: size/L

#1310 feat(server): support setting custom domain for application
  server/src/application/application.controller.ts
  server/src/gateway/apisix-custom-cert.service.ts
  server/src/gateway/apisix.service.ts
  server/src/gateway/entities/runtime-domain.ts
  server/src/gateway/runtime-domain-task.service.ts
  server/src/gateway/runtime-domain.service.ts
Labels: size/XL

#1338 feat(web): support setting custom domain for application
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/applications.ts
  web/src/chakraTheme.ts
  web/src/pages/app/functions/mods/EditorPanel/EditDomain.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/service.ts
  web/src/pages/globalStore.ts
Labels: size/L

#1341 build: update client header buffer size for apisix
  build/charts/apisix/values.yaml
Labels: size/XS

#1339 refactor(server): separate update of debug info from function update
  server/src/function/dto/update-function-debug.dto.ts
  server/src/function/dto/update-function.dto.ts
  server/src/function/function.controller.ts
  server/src/function/function.service.ts
Labels: size/M

#1340 refactor(web): separate update of debug info from function update
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/apps.ts
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/service.ts
Labels: size/M

#1342 fix(web): fix rendering issues when custom domain not exist
  web/src/pages/app/functions/mods/EditorPanel/EditDomain.tsx
Labels: size/XS
