Repository labring/laf, pull requests merged in 2023-03, with the labels that each got.

#875 fix(server): some resources missing when deleting app
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/application/application-task.service.ts
  server/src/application/application.module.ts
  server/src/application/application.service.ts
  server/src/application/configuration.service.ts
  server/src/application/dto/update-application.dto.ts
  server/src/constants.ts
  server/src/database/policy/policy.service.ts
  server/src/function/function.service.ts
  server/src/gateway/bucket-domain.service.ts
  server/src/region/bundle.service.ts
  server/src/storage/storage.service.ts
  server/src/trigger/trigger.service.ts
  server/src/website/website.service.ts
Labels: size/L

#879 fix(web): fix MoreButton tooltip and npm package deletion confirm tip
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/MoreButton/index.tsx
  web/src/pages/app/database/CollectionListPanel/index.tsx
  web/src/pages/app/database/PolicyListPanel/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/storages/mods/StorageListPanel/index.tsx
Labels: size/M

#884 feat(cli): cli invoke function support parameters (#842)
  cli/src/action/function/index.ts
  cli/src/api/debug.ts
  cli/src/command/function/index.ts
Labels: size/M

#886 fix(cli): remove private npm mirror and replace AxiosRequestConfig to any
  cli/package-lock.json
  cli/src/action/function/index.ts
  cli/src/action/website/index.ts
  cli/src/api/debug.ts
  cli/src/command/website/index.ts
  cli/src/util/request.ts
Labels: size/M

#893 feat(cli): rename name.meta.yaml to name.yaml
  cli/src/common/constant.ts
Labels: size/XS

#899 fix(cli): fix publish package ignore file
  cli/package.json
  cli/src/action/application/index.ts
  cli/src/common/constant.ts
  cli/template/gitignore
Labels: size/XS

#902 fix(README): add chatGPT example
  README.md
Labels: size/XS

#894 feat(subscription): impl subscription and account
  .vscode/settings.json
  deploy/scripts/install-on-linux.sh
  server/fix-local-envs.sh
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/account/account.controller.ts
  server/src/account/account.module.ts
  server/src/account/account.service.ts
  server/src/account/dto/create-charge-order.dto.ts
  server/src/account/payment/payment-channel.service.ts
  server/src/account/payment/types.ts
  server/src/account/payment/wechat-pay.service.ts
  server/src/app.module.ts
  server/src/application/application-task.service.ts
  server/src/application/application.controller.ts
  server/src/application/application.service.ts
  server/src/auth/application.auth.guard.ts
  server/src/auth/auth.module.ts
  server/src/constants.ts
  server/src/initializer/initializer.service.ts
  server/src/instance/instance-task.service.ts
  server/src/region/bundle.service.ts
  server/src/region/region.service.ts
  server/src/subscription/dto/create-subscription.dto.ts
  server/src/subscription/dto/renew-subscription.dto.ts
  server/src/subscription/dto/upgrade-subscription.dto.ts
  server/src/subscription/renewal-task.service.ts
  server/src/subscription/subscription-task.service.ts
  server/src/subscription/subscription.controller.ts
  server/src/subscription/subscription.module.ts
  server/src/subscription/subscription.service.ts
  server/src/utils/number.ts
  server/src/utils/random.ts
Labels: size/XXL

#904 feat(web): add subscription and wechat pay
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/App.css
  web/src/apis/typing.d.ts
  web/src/apis/v1/accounts.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/applications.ts
  web/src/apis/v1/subscriptions.ts
  web/src/components/ChargeButton/index.tsx
  web/src/components/FileUpload/index.module.scss
  web/src/constants/index.ts
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/app/setting/AppEnvList/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
  web/src/pages/globalStore.ts
  web/src/pages/home/mods/CreateAppModal/BundleItem/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/pages/home/mods/List/BundleInfo.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/pages/home/service.ts
  web/src/utils/format.ts
  web/src/utils/request.ts
Labels: size/XL

#907 feat(docs): add quick start todo
  README.md
  README_en.md
  docs/.vitepress/config.js
  docs/doc-images/AppID.png
  docs/doc-images/create-function.png
  docs/doc-images/create-gather.png
  docs/doc-images/todo-demo.png
  docs/guide/quick-start/Todo.md
  docs/guide/quick-start/login.md
Labels: size/L

#908 fix(server): add max renewal time in bundle; fix subscription price
  server/prisma/schema.prisma
  server/src/initializer/initializer.service.ts
  server/src/subscription/subscription.controller.ts
  server/src/subscription/subscription.service.ts
Labels: size/M

#911 doc: fix login example
  docs/.vitepress/config.js
  docs/guide/quick-start/login.md
Labels: size/S

#914 refactor subscription dialog experience
  .vscode/settings.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/ChargeButton/index.tsx
  web/src/components/ConfirmButton/index.tsx
  web/src/components/CopyText/index.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/JSONViewer.tsx
  web/src/components/IconText/index.tsx
  web/src/layouts/Function.tsx
  web/src/pages/app/database/mods/DeleteCollectionModal/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/mods/SideBar/index.module.scss
  web/src/pages/app/setting/AppInfoList/InfoDetail/index.module.scss
  web/src/pages/app/setting/AppInfoList/InfoDetail/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/globalStore.ts
  web/src/pages/home/index.tsx
  web/src/pages/home/mods/CreateAppModal/BundleItem/index.tsx
  web/src/pages/home/mods/CreateAppModal/RuntimeItem/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/pages/home/mods/DeleteAppModal/index.tsx
  web/src/pages/home/mods/Empty/index.module.scss
  web/src/pages/home/mods/Empty/index.tsx
  web/src/pages/home/mods/List/BundleInfo.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/pages/home/mods/StatusBadge/index.module.scss
Labels: size/XL

#919 fix(web): fix some dark mode ui bugs
  web/src/components/DependenceList/index.module.scss
  web/src/components/DependenceList/index.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/setting/UserInfo/AuthDetail/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
Labels: size/M

#922 feat(cli): upgrade s3 sdk version
  cli/package-lock.json
  cli/package.json
  cli/src/action/storage/index.ts
  cli/src/action/storage/s3.ts
Labels: size/M

#915 refactor(web): upgrade icon
  web/public/favicon.ico
  web/public/logo.png
  web/src/layouts/Basic.tsx
  web/src/pages/home/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/S

#924 fix(server): fix bucket name regex
  server/src/storage/dto/create-bucket.dto.ts
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/storages/mods/CreateBucketModal/index.tsx
Labels: size/S

#925 feat(server): add limit to update app state depends on subscription state
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
  server/src/application/application.controller.ts
  server/src/subscription/subscription.controller.ts
Labels: size/M

#927 chore: remove contrib docs of laf web
  contribution/zh_CN/images/change-redirect-uri.png
  contribution/zh_CN/images/configure-proxy-pattern.png
  contribution/zh_CN/images/configure-rule-in-whistle-console.png
  contribution/zh_CN/images/create-proxy-pattern.png
  contribution/zh_CN/images/install-switchy-omega.png
  contribution/zh_CN/images/open-switchy-omega.png
  contribution/zh_CN/images/translate-0.png
  contribution/zh_CN/images/translate-1.png
  contribution/zh_CN/images/translate-2.png
  contribution/zh_CN/images/whistl-in-laf-web.png
  contribution/zh_CN/web.md
Labels: size/M

#897 feat(server): new authentication implements
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/auth/auth.module.ts
  server/src/auth/authentication.controller.ts
  server/src/auth/authentication.service.ts
  server/src/auth/dto/bind-phone.dto.ts
  server/src/auth/dto/bind-username.dto.ts
  server/src/auth/dto/passwd-reset.dto.ts
  server/src/auth/dto/passwd-signin.dto.ts
  server/src/auth/dto/passwd-signup.dto.ts
  server/src/auth/dto/phone-signin.dto.ts
  server/src/auth/dto/send-phone-code.dto.ts
  server/src/auth/phone/phone.controller.ts
  server/src/auth/phone/phone.service.ts
  server/src/auth/phone/sms.service.ts
  server/src/auth/types.ts
  server/src/auth/user-passwd/user-password.controller.ts
  server/src/auth/user-passwd/user-password.service.ts
  server/src/constants.ts
  server/src/initializer/initializer.service.ts
  server/src/main.ts
  server/src/user/dto/user.response.ts
  server/src/user/user.service.ts
  server/src/utils/crypto.ts
Labels: size/XXL

#910 feat(web): impl new signup & signin method
  web/.env
  web/package.json
  web/pnpm-lock.yaml
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/auth.ts
  web/src/assets/login_bg.svg
  web/src/chakraTheme.ts
  web/src/layouts/Auth/index.module.scss
  web/src/layouts/Auth/index.tsx
  web/src/layouts/Header/UserSetting/index.tsx
  web/src/pages/auth/service.ts
  web/src/pages/auth/signin/index.tsx
  web/src/pages/auth/signin/mods/LoginByPasswordPanel/index.tsx
  web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
  web/src/pages/auth/signup/index.tsx
  web/src/pages/auth/store.ts
  web/src/routes/index.tsx
  web/src/utils/request.ts
Labels: size/XXL

#934 fix(server): change password signup phone filed to optional
  server/src/auth/dto/passwd-signup.dto.ts
Labels: size/S

#935 fix: web signup phone err
  web/src/pages/auth/signup/index.tsx
  web/src/routes/index.tsx
Labels: size/M

#937 fix(server): fix init auth provider params
  .vscode/settings.json
  server/src/initializer/initializer.service.ts
Labels: size/XS

#938 fix: sign up provider err
  web/src/pages/auth/signup/index.tsx
Labels: size/XS

#921 doc: add cli README.md
  cli/README.md
Labels: size/M

#943 fix(server): deal with existed app without namespace
  server/src/instance/instance.service.ts
Labels: size/M

#940 fix(web): update data use merge mode
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/database/service.ts
  web/src/pages/app/storages/mods/CreateFolderModal/index.tsx
  web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
Labels: size/M

#944 fix(server): add regex for environment name
  server/src/application/dto/create-env.dto.ts
Labels: size/XS

#945 fix(server): stuck-starting instance blocked the task handler
  .vscode/settings.json
  server/src/instance/instance-task.service.ts
Labels: size/M

#948 doc: add function param and data query
  docs/.vitepress/config.js
  docs/doc-images/appList.png
  docs/doc-images/create-function.png
  docs/doc-images/db.png
  docs/doc-images/file.png
  docs/doc-images/function.png
  docs/guide/db/index.md
  docs/guide/db/query.md
  docs/guide/function/call-function-in-client.md
  docs/guide/function/function-param.md
  docs/guide/function/index.md
  docs/guide/index.md
Labels: size/L

#950 refactor(web): updrage npm dependencies
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/FileUpload/index.tsx
  web/src/pages/app/database/store.ts
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/app/functions/store.ts
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/storages/store.ts
  web/src/pages/auth/store.ts
  web/src/pages/customSetting.ts
  web/src/pages/globalStore.ts
  web/src/pages/home/mods/List/index.tsx
Labels: size/L

#954 chore(deploy): remove casdoor charts
  deploy/build/charts/casdoor/.helmignore
  deploy/build/charts/casdoor/Chart.yaml
  deploy/build/charts/casdoor/README.md
  deploy/build/charts/casdoor/templates/NOTES.txt
  deploy/build/charts/casdoor/templates/_helpers.tpl
  deploy/build/charts/casdoor/templates/config.yaml
  deploy/build/charts/casdoor/templates/deployment.yaml
  deploy/build/charts/casdoor/templates/hpa.yaml
  deploy/build/charts/casdoor/templates/ingress.yaml
  deploy/build/charts/casdoor/templates/init_data.yaml
  deploy/build/charts/casdoor/templates/local-cdn-shim.yaml
  deploy/build/charts/casdoor/templates/service.yaml
  deploy/build/charts/casdoor/templates/serviceaccount.yaml
  deploy/build/charts/casdoor/templates/tests/test-connection.yaml
  deploy/build/charts/casdoor/token_jwt_key.key
  deploy/build/charts/casdoor/token_jwt_key.pem
  deploy/build/charts/casdoor/values.yaml
  deploy/build/charts/postgresql/.helmignore
  deploy/build/charts/postgresql/Chart.yaml
  deploy/build/charts/postgresql/LICENSE
  deploy/build/charts/postgresql/README.md
  deploy/build/charts/postgresql/configs/README.md
  deploy/build/charts/postgresql/templates/NOTES.txt
  deploy/build/charts/postgresql/templates/_helpers.tpl
  deploy/build/charts/postgresql/templates/configmap.yaml
  deploy/build/charts/postgresql/templates/cronjob.yaml
  deploy/build/charts/postgresql/templates/service.yaml
  deploy/build/charts/postgresql/templates/statefulset.yaml
  deploy/build/charts/postgresql/values.yaml
  deploy/build/images/shim/ImageList
  deploy/build/start.sh
Labels: size/XXL

#956 feat(server): support website custom domain ssl cert auto-gen
  deploy/build/charts/laf-server/templates/cert-issuer.yaml
  server/src/constants.ts
  server/src/gateway/apisix-custom-cert.service.ts
  server/src/gateway/apisix.service.ts
  server/src/gateway/gateway.module.ts
  server/src/gateway/website-task.service.ts
  server/src/instance/instance.service.ts
  server/src/region/cluster/cluster.service.ts
Labels: wip, size/L

#957 fix(server): fixed the error of repeatedly deleting website routes
  server/src/gateway/website-task.service.ts
Labels: size/XS

#951 feat(server): add check if password had binded
  server/src/auth/dto/passwd-check.dto.ts
  server/src/auth/user-passwd/user-password.controller.ts
  server/src/auth/user-passwd/user-password.service.ts
Labels: size/M

#955 refactor(web): optimize the tag selection
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/chakraTheme.ts
  web/src/chakraThemeDark.ts
  web/src/components/InputTag/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/L

#941 feat: fix login bg && add welcome text
  web/src/chakraThemeDark.ts
  web/src/layouts/Auth/index.module.scss
  web/src/layouts/Auth/index.tsx
  web/src/layouts/Header/UserSetting/index.tsx
  web/src/layouts/LoginReg.tsx
Labels: size/M

#958 doc: add db query
  docs/.vitepress/config.js
  docs/guide/db/actions.md
  docs/guide/db/policy.md
  docs/guide/db/query.md
  docs/guide/function/call-function-in-client.md
  docs/guide/function/use-function.md
Labels: size/XL

#959 fix(server): add website count limit, opt website task
  .vscode/settings.json
  server/src/gateway/apisix-custom-cert.service.ts
  server/src/gateway/website-task.service.ts
  server/src/storage/storage.module.ts
  server/src/website/website.controller.ts
  server/src/website/website.module.ts
Labels: size/L

#960 fix(deploy): upgrade minio version to fix CVE-2023-28432
  deploy/build/charts/minio/values.yaml
Labels: size/XS

#963 fix(web): add types for ctx.request
  web/src/components/Editor/typesResolve/globals.ts
  web/src/components/Editor/typesResolve/requestType.ts
Labels: size/L

#964 fix(server): error on deleting cronjob; app stucked in starting
  server/src/instance/instance-task.service.ts
  server/src/trigger/cron-job.service.ts
  server/src/trigger/trigger-task.service.ts
Labels: size/XL

#965 fix(server): fixed illegal removal of unowned trigger
  server/src/trigger/trigger.controller.ts
  server/src/trigger/trigger.service.ts
Labels: size/S

#972 doc: add website hosting and laf-cli
  docs/.vitepress/config.js
  docs/doc-images/add-polocy.png
  docs/doc-images/creat-bucket.png
  docs/doc-images/creat-polocy.png
  docs/doc-images/creat-token.png
  docs/doc-images/open-website.png
  docs/doc-images/polocy-db-data.png
  docs/doc-images/website-hosting.png
  docs/guide/cli/index.md
  docs/guide/db/policy.md
  docs/guide/db/query.md
  docs/guide/website-hosting/index.md
  docs/index.md
Labels: size/L

#976 fix(server): rm minio alias init in boot, fix multi region limit;
  server/src/account/account.service.ts
  server/src/app.module.ts
  server/src/database/database.service.ts
  server/src/initializer/initializer.service.ts
  server/src/instance/instance.service.ts
  server/src/main.ts
  server/src/storage/minio/minio.service.ts
Labels: size/M

#978 feat(web): generate function code with AI prompt
  .vscode/settings.json
  web/public/favicon.ico
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/public/logo.png
  web/public/logo_light.png
  web/public/logo_text.png
  web/src/components/Editor/FunctionEditor.tsx
  web/src/layouts/Header/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/storages/mods/UploadButton/index.tsx
  web/src/pages/auth/signin/index.tsx
  web/src/pages/auth/signup/index.tsx
Labels: size/L

#979 fix(web): remove withCredentials
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
  web/src/utils/request.ts
Labels: size/S

#980 fix(server): cancel namespace removal while stopping app
  server/src/instance/instance-task.service.ts
  server/src/instance/instance.service.ts
Labels: size/S

#983 fix(server): bucket deletion didn't remove related website
  server/src/storage/bucket-task.service.ts
Labels: size/L

#986 feat(server): add notes field to region,bundle,pay,auth
  server/prisma/schema.prisma
Labels: size/M

#988 fix(server): fix instance task error
  server/src/instance/instance-task.service.ts
Labels: size/XS

#985 style(web): Responsive styles for home page
  web/src/pages/home/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/pages/home/mods/StatusBadge/index.module.scss
  web/src/pages/home/mods/StatusBadge/index.tsx
Labels: size/S

#990 fix(server): add existing check in creating phase of tasks
  server/src/gateway/apisix.service.ts
  server/src/gateway/bucket-domain-task.service.ts
  server/src/gateway/runtime-domain-task.service.ts
  server/src/gateway/website-task.service.ts
Labels: size/L

#993 fix(server): return notes fields in region & bundles
  deploy/build/charts/laf-server/templates/cert-issuer.yaml
  server/prisma/schema.prisma
  server/src/region/region.service.ts
Labels: size/XS

#994 fix: phone register(web)
  web/pnpm-lock.yaml
  web/src/pages/auth/signin/index.tsx
  web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
Labels: size/XXL
