Repository labring/laf, pull requests merged in 2023-12, with the labels that each got.

#1717 fix(server): fix get_client_ip method, use x-forwarded-fro first
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/support/utils.ts
  server/src/authentication/email/email.controller.ts
  server/src/authentication/phone/phone.controller.ts
  server/src/utils/getter.ts
Labels: size/M

#1720 doc: deprecated the interceptor fn without next method
  docs/.vitepress/config.js
  docs/guide/function/call-function.md
  docs/guide/function/interceptor.md
  docs/guide/index.md
Labels: size/L

#1721 chore(runtime): update cloud sdk version in runtime
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
Labels: size/XS

#1723 fix(web): cannot update database record with ObjectId #1524
  web/package-lock.json
  web/package.json
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
Labels: size/M

#1725 fix(server): fix runtime logging interface not authenticated
  server/src/application/pod.controller.ts
  server/src/log/log.controller.ts
Labels: size/S

#1727 fix(server): Fix logging interface error return
  server/src/log/log.controller.ts
Labels: size/XS

#1729 feat(runtime): add cloud.storage api in cloud sdk
  packages/cloud-sdk/package-lock.json
  packages/cloud-sdk/package.json
  packages/cloud-sdk/src/cloud.interface.ts
  packages/cloud-sdk/src/cloud.ts
  packages/cloud-sdk/src/storage.ts
  runtimes/nodejs/package.json
  runtimes/nodejs/src/support/cloud-sdk.ts
  web/src/components/Editor/globalDefinition.ts
  web/src/components/Editor/typesResolve/index.ts
Labels: size/L

#1732 feat(cloud-sdk): add url api to cloud sdk
  packages/cloud-sdk/package-lock.json
  packages/cloud-sdk/package.json
  packages/cloud-sdk/src/storage.ts
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
Labels: size/M

#1731 fix(web): jsonviewer support to render large data
  web/package-lock.json
  web/package.json
  web/src/components/Editor/JSONViewer.tsx
  web/src/components/Editor/index.scss
  web/src/components/Pagination/index.tsx
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.scss
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/database/PolicyDataList/index.tsx
Labels: size/L

#1726 doc: opt db-ql documents
  docs/guide/db/find.md
  packages/database-ql/src/result-types.ts
Labels: size/XS

#1733 fix(services): Changing exporter penalty rules
  services/runtime-exporter/src/handler/get-runtime-metrics.ts
  services/runtime-exporter/src/helper/cluster.service.ts
  services/runtime-exporter/src/index.ts
  services/runtime-exporter/tsconfig.dev.json
Labels: size/M

#1734 refactor(cloud-sdk): refacct readFile returns in cloud-sdk
  packages/cloud-sdk/package-lock.json
  packages/cloud-sdk/package.json
  packages/cloud-sdk/src/storage.ts
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
Labels: size/M

#1735 refactor(cloud-sdk): refactor listFiles paramsof cloud sdk
  packages/cloud-sdk/package-lock.json
  packages/cloud-sdk/package.json
  packages/cloud-sdk/src/storage.ts
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
Labels: size/S

#1738 refactor(db-proxy): refactor accessor constructor in database-proxy, add objectid type as global in runtime;
  .vscode/settings.json
  packages/cloud-sdk/package-lock.json
  packages/cloud-sdk/package.json
  packages/database-proxy/README.md
  packages/database-proxy/package-lock.json
  packages/database-proxy/package.json
  packages/database-proxy/src/accessor/mongo.ts
  packages/database-proxy/tsconfig.json
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/db.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/support/cloud-sdk.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/engine/types.ts
  server/package-lock.json
  server/package.json
  server/src/database/database.service.ts
  server/src/main.ts
  server/src/system-database.ts
  web/src/components/Editor/globalDefinition.ts
  web/src/components/Editor/typesResolve/globals.ts
  web/src/components/Editor/typesResolve/objectidType.ts
Labels: size/XL

#1743 feat(runtime): support LF_NODE_MODULES_CACHE to control if offline deps installation
  runtimes/nodejs/init.sh
Labels: size/S

#1742 fix(cli): fix cli env command description
  cli/src/command/environment/index.ts
Labels: size/XS

#1740 chore(web): fix styles & optimize tips & add running cancel
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/ChargeButton/index.tsx
  web/src/components/Resize/index.tsx
  web/src/hooks/useResizable.ts
  web/src/pages/app/database/index.tsx
  web/src/pages/app/functions/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/mods/TriggerModal/AddTriggerModal/index.tsx
  web/src/pages/app/functions/mods/TriggerModal/index.tsx
  web/src/pages/app/functions/mods/TriggerModal/service.ts
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/PieCard/index.tsx
  web/src/pages/app/setting/SysSetting/CustomDomain/index.tsx
  web/src/pages/app/setting/UserSetting/BillingDetails/index.tsx
  web/src/pages/app/setting/UserSetting/RechargeHistory/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/app/storages/index.tsx
  web/src/pages/app/storages/mods/CreateBucketModal/index.tsx
  web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
  web/src/pages/app/storages/mods/StorageListPanel/index.tsx
  web/src/pages/auth/signin/index.tsx
  web/src/pages/customSetting.ts
  web/src/pages/globalStore.ts
  web/src/pages/home/mods/List/index.tsx
Labels: size/L

#1736 chore(ci): add digest for images of the pr
  .github/workflows/dockerize-runtime-exporter.yml
  .github/workflows/dockerize-runtime-nodejs.yml
  .github/workflows/dockerize-server.yml
  .github/workflows/dockerize-web.yml
Labels: size/M

#1745 fix(web&server): Fix billing inquiry time boundary problem
  server/src/billing/billing.service.ts
  web/src/pages/app/setting/UserSetting/Usage/index.tsx
Labels: size/M

#1747 fix(cli): fix pkg not dotenv
  cli/package-lock.json
  cli/package.json
Labels: size/XS

#1746 doc: optimize wording
  docs/guide/laf-assistant/index.md
Labels: size/XS

#1748 fix(server): billing inquiry statistics field fixes
  server/src/billing/billing.service.ts
Labels: size/XS

#1752 refactor(web): add default phone to change password and change phone
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/CommonIcon/index.tsx
  web/src/constants/index.ts
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/logs/index.module.scss
  web/src/pages/app/logs/index.tsx
  web/src/pages/app/logs/service.ts
  web/src/pages/app/setting/SysSetting/CommonSetting/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/Mods/PasswordEditor.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/Mods/PhoneEditor.tsx
Labels: size/L

#1714 refactor(runtime): refactor storage proxy
  cli/src/command/environment/index.ts
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/storage-server.ts
Labels: size/L

#1759 chore: only show func name of last depth
  web/src/pages/app/functions/mods/HeadPanel/index.tsx
Labels: size/XS
