Repository labring/laf, pull requests merged in 2023-08, with the labels that each got.

#1434 chore(ci): rebuild sharp for arm64 and cache node_modules
  .github/workflows/dockerize-server.yml
  server/package-lock.json
Labels: size/S

#1436 fix(server): fix undefined field `memberOf` of minio user
  server/src/storage/minio/minio.service.ts
Labels: size/XS

#1435 refactor(web): add template category constant & add language and color to statusbar
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/ColorModeSwitch/index.tsx
  web/src/components/CommonIcon/index.tsx
  web/src/components/LanguageSwitch/index.tsx
  web/src/components/Pagination/index.tsx
  web/src/constants/index.ts
  web/src/layouts/Header/index.tsx
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/app/setting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/AppMonitor/PieCard/index.tsx
  web/src/pages/app/setting/AppMonitor/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateCard/TemplateCard.tsx
  web/src/pages/functionTemplate/index.tsx
  web/src/pages/homepage/language.tsx
  web/src/pages/homepage/navbar.tsx
Labels: size/L

#1423 fix(web): change releasing as app phase
  web/src/constants/index.ts
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/home/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/pages/home/mods/StatusBadge/index.tsx
Labels: size/M

#1430 feat(server): Add a global http interceptor
  server/src/app.interceptor.ts
  server/src/app.module.ts
  server/src/constants.ts
  server/src/gateway/website-task.service.ts
  server/src/interceptor/dto/http-interceptor.dto.ts
  server/src/interceptor/http-interceptor.service.ts
  server/src/interceptor/interceptor.module.ts
Labels: size/L

#1437 fix(server): increase the request payload limit
  services/log-server/src/handler/get-function-log.ts
  services/log-server/src/index.ts
Labels: size/XS

#1439 chore(log): add env for request payload limit
  services/log-server/src/config.ts
  services/log-server/src/index.ts
Labels: size/XS

#1438 fix(server): relock check of domain tls for too long
  server/package-lock.json
  server/package.json
  server/src/gateway/runtime-domain-task.service.ts
  server/src/gateway/website-task.service.ts
Labels: size/M

#1441 doc: add oss github action
  docs/doc-images/oss-get-sts.png
  docs/guide/website-hosting/index.md
Labels: size/M

#1447 fix(cli): fix cannot read properties baseDir
  cli/src/util/sys.ts
Labels: size/XS

#1442 feat(server): support resource group
  server/src/app.module.ts
  server/src/application/application.controller.ts
  server/src/application/application.service.ts
  server/src/authentication/application.auth.guard.ts
  server/src/billing/billing.controller.ts
  server/src/group/dto/create-group.dto.ts
  server/src/group/dto/find-group-invite-code.dto.ts
  server/src/group/dto/find-group-member.dto.ts
  server/src/group/dto/get-group-invite-code-detail.dto.ts
  server/src/group/dto/update-group-invite-code.dto.ts
  server/src/group/dto/update-group-member-role.dto.ts
  server/src/group/dto/update-group.dto.ts
  server/src/group/entities/group-application.ts
  server/src/group/entities/group-invite-code.ts
  server/src/group/entities/group-member.ts
  server/src/group/entities/group.ts
  server/src/group/group-application/group-application.controller.ts
  server/src/group/group-application/group-application.service.ts
  server/src/group/group-auth.guard.ts
  server/src/group/group-invite/group-invite.controller.ts
  server/src/group/group-invite/group-invite.service.ts
  server/src/group/group-member/group-member.controller.ts
  server/src/group/group-member/group-member.service.ts
  server/src/group/group-role.decorator.ts
  server/src/group/group.controller.ts
  server/src/group/group.module.ts
  server/src/group/group.service.ts
  server/src/utils/decorator.ts
Labels: size/XXL

#1444 feat(web): support resource group
  .vscode/settings.json
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/App.css
  web/src/App.tsx
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/group.ts
  web/src/components/CommonIcon/index.tsx
  web/src/components/MoreButton/index.tsx
  web/src/components/Panel/index.tsx
  web/src/components/Resize/index.tsx
  web/src/constants/index.ts
  web/src/main.tsx
  web/src/pages/app/collaboration/CollaborateButton/index.tsx
  web/src/pages/app/collaboration/Invited/index.tsx
  web/src/pages/app/collaboration/Invited/logo_invite.tsx
  web/src/pages/app/collaboration/service.ts
  web/src/pages/app/database/index.tsx
  web/src/pages/app/functions/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/DeployButton/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/mods/HeadPanel/FunctionDetailPopOver.tsx
  web/src/pages/app/functions/mods/HeadPanel/index.tsx
  web/src/pages/app/functions/service.ts
  web/src/pages/app/functions/store.ts
  web/src/pages/app/index.tsx
  web/src/pages/app/mods/StatusBar/RecycleBinModal/index.tsx
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/auth/signin/mods/LoginByPasswordPanel/index.tsx
  web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
  web/src/pages/auth/signup/index.tsx
  web/src/pages/customSetting.ts
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/routes/index.tsx
  web/src/utils/request.ts
  web/tailwind.config.cjs
Labels: size/XXL

#1455 fix(web): add develop-token to load package
  web/src/components/Editor/typesResolve/index.ts
Labels: size/XS

#1452 fix(server): reapply hpa and check spec when spec changes
  server/src/application/application.controller.ts
  server/src/billing/resource.controller.ts
  server/src/instance/instance.service.ts
Labels: size/M

#1453 fix(server): check app auth by createdBy
  server/src/application/application.service.ts
  server/src/authentication/application.auth.guard.ts
Labels: size/S

#1454 fix(runtime): function source leakage caused by type hint interface
  runtimes/nodejs/src/handler/typings.ts
Labels: size/S

#1456 fix(web): fix statusbar change app specific display
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/home/mods/CreateAppModal/AutoscalingControl/index.tsx
  web/src/pages/home/mods/CreateAppModal/BundleControl/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/XL

#1457 ci(docs): refactor docs build action
  .github/actions/build-docs/action.yml
  .github/workflows/deploy-doc.yml
  .github/workflows/link-pr.yml
  .github/workflows/link-schedule.yml
  .lycheeignore
Labels: size/L

#1458 fix(web): fix display when specification not in bundle
  web/src/pages/home/mods/CreateAppModal/BundleControl/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/M

#1459 fix(server): create default group when check miss
  server/src/authentication/application.auth.guard.ts
Labels: size/XS

#1463 fix(web): keep function expanded when making modifications
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/mods/VersionHistoryPanel/index.tsx
  web/src/pages/app/mods/SideBar/index.tsx
Labels: size/L

#1462 deploy: add metrics-server
  deploy/install-on-linux.sh
Labels: size/XS

#1448 feat(runtime): check circular dependency
  runtimes/nodejs/src/support/function-engine/cache.ts
  runtimes/nodejs/src/support/function-engine/engine.ts
  runtimes/nodejs/src/support/function-engine/require.ts
  runtimes/nodejs/src/support/function-engine/types.ts
  runtimes/nodejs/src/support/function-engine/vm.ts
Labels: size/M

#1470 fix(runtime): vm add support for Float32Array #1368
  runtimes/nodejs/src/support/function-engine/vm.ts
Labels: size/XS

#1468 feat(server): support resource monitor
  .vscode/settings.json
  build/charts/laf-server/templates/deployment.yaml
  build/charts/minio/values.yaml
  build/prometheus-helm.yaml
  build/start.sh
  e2e/.gitignore
  e2e/.prettierrc
  e2e/2-monitor/00-query.test.ts
  e2e/config.ts
  e2e/package-lock.json
  e2e/package.json
  lerna.json
  server/src/app.module.ts
  server/src/constants.ts
  server/src/initializer/initializer.service.ts
  server/src/monitor/dto/query-metrics.dto.ts
  server/src/monitor/monitor.controller.ts
  server/src/monitor/monitor.module.ts
  server/src/monitor/monitor.service.ts
  server/src/region/entities/region.ts
Labels: size/L

#1471 feat(web): support resource monitor
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/group.ts
  web/src/apis/v1/monitor.ts
  web/src/pages/app/mods/StatusBar/MonitorBar/index.tsx
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/app/setting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/AppMonitor/PieCard/index.tsx
  web/src/pages/app/setting/AppMonitor/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/globalStore.ts
  web/src/utils/format.ts
Labels: size/XL

#1450 feat(web): support real name authentication
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/v1/api-auto.d.ts
  web/src/layouts/Basic/RealNameWarn.tsx
  web/src/layouts/Basic/index.tsx
  web/src/pages/app/setting/UserInfo/AuthDetail/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/setting/UserSetting/index.tsx
  web/src/pages/app/setting/UserSetting/useTabMatch.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/pages/home/mods/Empty/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/pages/siteSetting.ts
Labels: size/XL

#1472 ci: laf doc preview during pr
  .github/workflows/doc-preview.yml
Labels: size/L

#1481 doc: fix quick start add function market & Pilot
  docs/.vitepress/config.js
  docs/doc-images/Laf-Pilot.png
  docs/doc-images/Laf-Pilot2.png
  docs/doc-images/function-market.png
  docs/doc-images/function-template.png
  docs/doc-images/my-template.png
  docs/guide/function/function-market.md
  docs/guide/function/pilot.md
  docs/guide/quick-start/Todo.md
Labels: size/L

#1482 fix(web): fix display when monitor data undefined
  web/src/pages/app/setting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/AppMonitor/index.tsx
Labels: size/XS

#1483 fix(build): fix prometheus network policy
  build/prometheus-helm.yaml
Labels: size/XS

#1484 refactor(web): add initial value to monitor bar width & click open detail
  web/src/pages/app/mods/StatusBar/MonitorBar/index.tsx
Labels: size/M

#1476 refactor(server): refactor function template
  server/src/function-template/dto/function-templates.dto.ts
  server/src/function-template/function-template.controller.ts
  server/src/function-template/function-template.service.ts
Labels: size/XL

#1485 fix(server): correct monitor metrics promql
  server/src/monitor/monitor.service.ts
Labels: size/XS

#1486 chore(build): add pvc for prometheus
  build/Kubefile
  build/images/shim/ImageList
  build/prometheus-helm.yaml
  build/start.sh
Labels: size/S

#1487 fix(web): fix pods list data & adjust create function ui
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/setting/AppMonitor/index.tsx
Labels: size/M

#1479 feat: support import/export application db
  .vscode/settings.json
  server/Dockerfile
  server/src/database/database.controller.ts
  server/src/database/database.service.ts
  server/src/database/dto/import-database.dto.ts
Labels: size/L

#1488 fix(build): fix build of laf mage and change the deployment of metering service
  build/Kubefile
  build/charts/laf-server/templates/metering.yaml
  build/images/shim/ImageList
  build/start.sh
  deploy/install-on-linux.sh
Labels: size/L

#1480 fix: fix change stream concurrency reconnect
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/support/db-change-stream.ts
  runtimes/nodejs/src/support/function-engine/cache.ts
Labels: size/M

#1490 fix(server): fix website hosting routes
  server/src/gateway/apisix.service.ts
  server/src/monitor/monitor.service.ts
Labels: size/XS

#1489 chore(build): localize prometheus helm charts
  build/charts/prometheus/kube-prometheus-stack-48.3.5.tgz
  build/charts/prometheus/prometheus-mongodb-exporter-3.2.0.tgz
  build/start.sh
  server/Dockerfile
Labels: size/S

#1491 fix(web): add unavailable page for monitor data & fix link of real name
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/CommonIcon/index.tsx
  web/src/pages/app/setting/AppMonitor/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateCard/index.tsx
Labels: size/L

#1493 chore(build): upgrade mongodb exporter
  build/charts/laf-server/values.yaml
  build/charts/prometheus-mongodb-exporter/Chart.yaml
  build/start.sh
Labels: size/XS

#1494 doc: fix login example param checking
  docs/guide/quick-start/login.md
Labels: size/XS

#1495 fix(server): change default interceptor policy
  server/src/interceptor/http-interceptor.service.ts
Labels: size/XS

#1499 fix(server): fix apisix try path routes
  server/src/gateway/apisix.service.ts
Labels: size/XS
