Repository labring/laf, pull requests merged in 2023-04, with the labels that each got.

#996 fix(web): fixed the path issue when clicking pathlink(#995)
  web/src/pages/app/storages/mods/PathLink/index.tsx
Labels: size/XS

#997 fix(server): check site deleting state in site creation
  server/src/website/website.controller.ts
Labels: size/XS

#1001 feat(web): add region info on logo
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/home/mods/List/index.tsx
Labels: size/M

#1002 feat(web): format code on save
  web/src/App.css
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/JSONViewer.tsx
  web/src/components/Editor/JsonEditor.tsx
  web/src/pages/home/mods/CreateAppModal/BundleItem/index.tsx
Labels: size/S

#1004 doc: update image and add cli-mind websocket laf client sdk
  .lycheeignore
  docs/.vitepress/config.js
  docs/doc-images/add-env.png
  docs/doc-images/add-packages.png
  docs/doc-images/create-injector.png
  docs/doc-images/edit-cloudfunction.png
  docs/doc-images/package-list.png
  docs/doc-images/publish-cloudfunction.png
  docs/doc-images/run-cloudfunction.png
  docs/guide/cli/index.md
  docs/guide/client-sdk/index.md
  docs/guide/db/policy.md
  docs/guide/function/call-function-in-client.md
  docs/guide/function/env.md
  docs/guide/function/index.md
  docs/guide/function/websocket.md
  docs/guide/index.md
  docs/guide/oss/index.md
  docs/guide/oss/use-sts-in-client.md
  docs/guide/quick-start/Todo.md
  docs/guide/quick-start/login.md
  docs/index.md
Labels: size/XL

#1006 fix: fix app url protocol error & update default url
  cli/src/action/application/index.ts
  cli/src/common/constant.ts
Labels: size/XS

#1010 optimize install-on-linux.sh
  deploy/scripts/install-on-linux.sh
Labels: size/XS

#1011 fix(web): appid confict if open 2 tabs
  web/src/apis/v1/accounts.ts
  web/src/apis/v1/applications.ts
  web/src/apis/v1/apps.ts
  web/src/apis/v1/auth.ts
  web/src/apis/v1/code2token.ts
  web/src/apis/v1/login.ts
  web/src/apis/v1/pat2token.ts
  web/src/apis/v1/pats.ts
  web/src/apis/v1/profile.ts
  web/src/apis/v1/regions.ts
  web/src/apis/v1/register.ts
  web/src/apis/v1/runtimes.ts
  web/src/apis/v1/subscriptions.ts
  web/src/layouts/Auth/index.tsx
  web/src/layouts/Function.tsx
  web/src/pages/app/database/CollectionDataList/mods/ColPanel/index.tsx
  web/src/pages/app/database/PolicyDataList/index.tsx
  web/src/pages/app/database/RightComponent/EditBox.tsx
  web/src/pages/app/database/mods/AddDataModal/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/FunctionDetailPopOver.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/TriggerModal/index.tsx
  web/src/pages/app/logs/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
  web/src/pages/app/storages/mods/StorageListPanel/index.tsx
  web/src/pages/auth/reset-password/index.tsx
  web/src/pages/auth/signin/mods/LoginByPasswordPanel/index.tsx
  web/src/pages/auth/signup/index.tsx
  web/src/pages/home/mods/Empty/index.tsx
Labels: size/L

#1014 feat(server): add account transaction
  server/prisma/schema.prisma
  server/src/account/account.controller.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/casdoor.service.ts
  server/src/constants.ts
  server/src/region/bundle.service.ts
  server/src/subscription/dto/upgrade-subscription.dto.ts
  server/src/subscription/renewal-task.service.ts
  server/src/subscription/subscription.controller.ts
Labels: size/L

#1016 chore: sealos does not support pulling multiple cluster images
  deploy/scripts/install-on-linux.sh
Labels: size/XS

#1005 feat(runtime): impl cloud function import and cache function
  runtimes/nodejs/package.json
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/constants.ts
  runtimes/nodejs/src/db.ts
  runtimes/nodejs/src/handler/db-proxy.ts
  runtimes/nodejs/src/handler/debug-func.ts
  runtimes/nodejs/src/handler/invoke-func.ts
  runtimes/nodejs/src/handler/router.ts
  runtimes/nodejs/src/handler/typings.ts
  runtimes/nodejs/src/support/cloud-sdk.ts
  runtimes/nodejs/src/support/function-engine/cache.ts
  runtimes/nodejs/src/support/function-engine/engine.ts
  runtimes/nodejs/src/support/function-engine/function.ts
  runtimes/nodejs/src/support/function-engine/index.ts
  runtimes/nodejs/src/support/function-engine/require.ts
  runtimes/nodejs/src/support/function-engine/types.ts
  runtimes/nodejs/src/support/function-engine/vm.ts
  runtimes/nodejs/src/support/logger.ts
  runtimes/nodejs/src/support/policy.ts
  runtimes/nodejs/src/support/token.ts
  runtimes/nodejs/src/support/utils.ts
Labels: size/XL

#1017 fix(server): check website hosting in bucket deletion, add error handle to tasks;
  deploy/build/charts/laf-web/templates/ingress.yaml
  deploy/build/charts/minio/templates/ingress.yaml
  deploy/build/images/shim/ImageList
  server/src/application/application-task.service.ts
  server/src/gateway/bucket-domain-task.service.ts
  server/src/gateway/runtime-domain-task.service.ts
  server/src/gateway/website-task.service.ts
  server/src/storage/bucket-task.service.ts
  server/src/storage/bucket.controller.ts
  server/src/storage/storage.service.ts
Labels: size/L

#1021 doc: fix logo and link
  docs/.vitepress/config.js
  docs/public/logo.png
  docs/public/zhuo.png
Labels: size/S

#1020 fix: route dashboard link
  web/public/homepage/logo_icon.svg
  web/public/homepage/wechat_01.svg
  web/public/homepage/wechat_02.svg
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/constants/index.ts
  web/src/pages/403.tsx
  web/src/pages/404.tsx
  web/src/pages/LoginCallback.tsx
  web/src/pages/app/mods/SideBar/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/auth/signin/mods/LoginByPasswordPanel/index.tsx
  web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
  web/src/pages/homepage/choice.tsx
  web/src/pages/homepage/hero.tsx
  web/src/pages/homepage/joinus.tsx
  web/src/pages/homepage/navbar.tsx
Labels: size/L

#1032 docs: update how to use the database
  docs/guide/client-sdk/index.md
  docs/guide/quick-start/login.md
Labels: size/XS

#1027 fix(web): Repair document link address
  web/src/pages/homepage/navbar.tsx
Labels: size/XS

#1031 doc: fix image and add http
  docs/.vitepress/config.js
  docs/doc-images/doc-app-list.png
  docs/doc-images/doc-db.png
  docs/doc-images/doc-function-list.png
  docs/doc-images/doc-policy.png
  docs/doc-images/doc-storage.png
  docs/doc-images/function-url.png
  docs/guide/function/call-function-in-http.md
  docs/screenshots.md
Labels: size/M

#1030 feat(cli): add ignore file
  cli/template/gitignore
Labels: size/XS

#1037 doc: fix function-in-client url error
  docs/guide/function/call-function-in-client.md
Labels: size/XS

#1039 feat: update @lafjs/cloud runtime version
  server/src/runtime-builtin-deps.ts
Labels: size/XS

#1038 fix: optimize invoke code prompts and documents
  packages/client-sdk/README.md
  packages/client-sdk/src/cloud.ts
Labels: size/M

#1040 feat(web): common error handler
  web/src/pages/app/database/mods/AddRulesModal/index.tsx
  web/src/pages/auth/signin/mods/LoginByPhonePanel/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/pages/home/mods/List/index.tsx
  web/src/utils/request.ts
Labels: size/M

#1045 fix(server): suspend cronjob after instance stopped
  packages/cloud-sdk/src/cloud.interface.ts
  server/src/instance/instance-task.service.ts
  server/src/instance/instance.module.ts
  server/src/trigger/cron-job.service.ts
  server/src/trigger/trigger.module.ts
Labels: size/M

#1043 feat(web): add homepage darkmode
  web/public/homepage/discord_hover.svg
  web/public/homepage/forumicon.svg
  web/public/homepage/github.svg
  web/public/homepage/language.svg
  web/public/homepage/menu.svg
  web/public/homepage/weixinicon.svg
  web/src/App.css
  web/src/components/CommonIcon/index.ts
  web/src/pages/homepage/ability.tsx
  web/src/pages/homepage/choice.tsx
  web/src/pages/homepage/footer.tsx
  web/src/pages/homepage/index.tsx
  web/src/pages/homepage/language.tsx
  web/src/pages/homepage/navbar.tsx
Labels: size/L

#1046 fix(web): add scrollbar
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/XS

#1048 feat(web): delete folder in storage (#1047)
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/hooks/useAwsS3.ts
  web/src/pages/app/storages/mods/FileList/index.tsx
Labels: size/M

#1049 fix(server): avoid acct-trans addition in free order
  deploy/build/charts/laf-server/templates/deployment.yaml
  deploy/build/charts/laf-server/values.yaml
  deploy/build/start.sh
  server/Dockerfile.alpine
  server/package.json
  server/src/account/account.controller.ts
  server/src/constants.ts
  server/src/gateway/apisix-custom-cert.service.ts
  server/src/subscription/renewal-task.service.ts
Labels: size/M

#1050 doc: improved cloud function related documents
  docs/doc-images/edit-cloudfunction.png
  docs/doc-images/function-body.png
  docs/doc-images/function-query.png
  docs/doc-images/getToken-parseToken.png
  docs/guide/function/call-function-in-client.md
  docs/guide/function/call-function-in-http.md
  docs/guide/function/call-function.md
  docs/guide/function/depend.md
  docs/guide/function/index.md
  docs/guide/function/use-function.md
  docs/guide/function/websocket.md
Labels: size/L

#1051 doc: add document for the interceptor
  docs/.vitepress/config.js
  docs/guide/function/interceptor.md
  docs/guide/function/websocket.md
Labels: size/M

#1052 feat(web): add ChatGPT example
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/functionTemplates.ts
Labels: size/M

#1055 feat(server): add func debug params, add envs update api
  server/prisma/schema.prisma
  server/src/application/environment.controller.ts
  server/src/application/environment.service.ts
  server/src/function/dto/update-function.dto.ts
  server/src/function/function.service.ts
Labels: size/M

#1057 doc: optimize cloud function document && add document search function
  docs/.vitepress/config.js
  docs/doc-images/change-package-version.png
  docs/doc-images/delete-package.png
  docs/doc-images/function-log.png
  docs/guide/function/call-function.md
  docs/guide/function/depend.md
  docs/guide/function/env.md
  docs/guide/function/logs.md
  docs/guide/function/use-function.md
  docs/package-lock.json
  docs/package.json
  docs/vite.config.js
Labels: size/L

#1058 refactor(web): update env modify modal
  .vscode/settings.json
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/apps.ts
  web/src/apis/v1/subscriptions.ts
  web/src/chakraTheme.ts
  web/src/chakraThemeDark.ts
  web/src/components/DependenceList/index.tsx
  web/src/components/EditableTable/index.tsx
  web/src/components/Editor/CodeViewer.tsx
  web/src/components/Editor/ENVEditor.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/JSONEditor.tsx
  web/src/components/Editor/JSONViewer.tsx
  web/src/components/IconText/index.tsx
  web/src/components/IconWrap/index.tsx
  web/src/components/InputTag/index.tsx
  web/src/constants/index.ts
  web/src/layouts/Function.tsx
  web/src/layouts/Header/UserSetting/index.tsx
  web/src/layouts/Header/index.tsx
  web/src/pages/app/database/CollectionDataList/mods/ColPanel/index.tsx
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/database/PolicyDataList/index.tsx
  web/src/pages/app/database/RightComponent/EditBox.tsx
  web/src/pages/app/database/mods/AddDataModal/index.tsx
  web/src/pages/app/database/mods/AddRulesModal/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/BodyParamsTab/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/setting/AppEnvList/index.tsx
  web/src/pages/app/setting/AppEnvList/service.ts
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/setting/UserInfo/AuthDetail/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/app/storages/mods/FileList/index.tsx
  web/src/pages/globalStore.ts
  web/src/pages/home/mods/CreateAppModal/BundleItem/index.tsx
  web/src/pages/home/mods/Empty/index.tsx
  web/src/pages/homepage/ability.tsx
  web/src/pages/homepage/choice.tsx
  web/src/pages/homepage/footer.tsx
  web/src/pages/homepage/globals.css
  web/src/pages/homepage/language.tsx
  web/src/pages/homepage/navbar.tsx
Labels: size/XL

#1059 fix(web): opt ide typings for response & request, opt function templates
  web/.env
  web/src/components/Editor/typesResolve/globals.ts
  web/src/components/Editor/typesResolve/requestType.ts
  web/src/components/Editor/typesResolve/responseType.ts
  web/src/components/Editor/typesResolve/streamType.ts
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/functionTemplates.ts
Labels: size/XL

#1061 refactor(web): editor scrollbar & colorMode fix
  web/src/components/Editor/CommonDiffEditor.tsx
  web/src/components/Editor/ENVEditor.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/JSONEditor.tsx
  web/src/pages/app/setting/AppEnvList/index.tsx
  web/src/pages/globalStore.ts
Labels: size/S

#1062 doc: optimize the search button style && add database quickstart
  docs/.vitepress/config.js
  docs/.vitepress/theme/custom.css
  docs/doc-images/dblist.jpg
  docs/guide/db/index.md
  docs/guide/db/quickstart.md
  docs/guide/function/depend.md
  docs/guide/function/index.md
Labels: size/L

#1064 doc: change start button name
  docs/.vitepress/config.js
Labels: size/XS

#1065 fix(server): check env name regex for batch update
  server/src/application/dto/create-env.dto.ts
  server/src/application/environment.controller.ts
Labels: size/S

#1066 fix(server): remove minio alias init
  server/src/storage/minio/minio.service.ts
Labels: size/M

#1056 ci: init e2e(check deployment and app create)
  .github/workflows/build-sealos-cluster-image.yml
  .github/workflows/dockerize-runtime-nodejs.yml
  .github/workflows/e2e.yml
  e2e/e2e.sh
  e2e/f1-payload.json
  e2e/f2-origin-payload.json
  e2e/f2-update-payload.json
Labels: size/L

#1060 ci: report broken links as an issue
  .github/workflows/link-schedule.yml
Labels: size/S

#1068 doc: database document optimization and hosting document optimization
  docs/.vitepress/config.js
  docs/doc-images/auto-build1.png
  docs/doc-images/auto-build2.png
  docs/guide/client-sdk/index.md
  docs/guide/db/add.md
  docs/guide/db/find.md
  docs/guide/function/use-function.md
  docs/guide/website-hosting/index.md
Labels: size/XL

#1054 feat(web): add status bar
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/database/PolicyListPanel/index.tsx
  web/src/pages/app/database/index.tsx
  web/src/pages/app/functions/index.tsx
  web/src/pages/app/functions/mods/ConsolePanel/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/logs/index.tsx
  web/src/pages/app/mods/SideBar/Icons.tsx
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/app/setting/AppInfoList/index.tsx
  web/src/pages/app/storages/index.tsx
Labels: size/L

#1070 feat(web): add loginpage darkmode
  web/src/layouts/Auth/index.module.scss
  web/src/layouts/Auth/index.tsx
  web/src/pages/auth/reset-password/index.tsx
  web/src/pages/auth/signin/index.tsx
  web/src/pages/auth/signup/index.tsx
Labels: size/M

#1072 fix(runtime): fix func logging order
  runtimes/nodejs/src/support/function-log.ts
  server/src/instance/instance-task.service.ts
Labels: size/XS

#1073 fix(server): use _id to sort logs instead of created_at
  server/src/function/function.service.ts
Labels: size/XS

#1074 feat(runtime): support process.env in runtime
  runtimes/nodejs/src/support/cloud-sdk.ts
  runtimes/nodejs/src/support/function-engine/vm.ts
Labels: size/XS

#1075 fix(server): fix waiting time in instance starting task
  server/src/instance/instance-task.service.ts
Labels: size/S

#1076 doc: optimize cloud function documents and database documents
  .lycheeignore
  docs/.vitepress/config.js
  docs/api/function.md
  docs/examples/alipay-pay.md
  docs/examples/aliyun-sms.md
  docs/examples/send-mail.md
  docs/examples/wechat-pay.md
  docs/guide/client-sdk/index.md
  docs/guide/db/actions.md
  docs/guide/db/add.md
  docs/guide/db/aggregate.md
  docs/guide/db/command.md
  docs/guide/db/del.md
  docs/guide/db/find.md
  docs/guide/db/quickstart.md
  docs/guide/db/update.md
  docs/guide/function/call-function-in-http.md
  docs/guide/function/faq.md
  docs/guide/function/interceptor.md
  docs/guide/function/logs.md
  docs/guide/function/use-function.md
  docs/guide/function/websocket.md
  docs/guide/oss/get-sts.md
  docs/guide/oss/use-sts-in-client.md
  docs/guide/quick-start/Todo.md
  docs/guide/quick-start/login.md
  docs/guide/website-hosting/index.md
  docs/index.md
Labels: size/XXL

#1077 feat(server): hot load environments for runtime instead of restarting runtime
  docs/diagrams/laf-arch-full.excalidraw
  docs/diagrams/laf-arch-simple.excalidraw
  docs/diagrams/laf-arch-simple.png
  e2e/f1-payload.json
  e2e/f2-origin-payload.json
  runtimes/nodejs/src/constants.ts
  runtimes/nodejs/src/db.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/support/cloud-sdk.ts
  runtimes/nodejs/src/support/db-change-stream.ts
  runtimes/nodejs/src/support/function-engine/vm.ts
  server/src/application/configuration.service.ts
  server/src/application/environment.service.ts
  server/src/constants.ts
Labels: size/XXL

#1079 feat(web): update environment variables without app restart
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/setting/AppEnvList/index.tsx
Labels: size/S

#1083 ci(e2e): wait api route in apisix ready
  .github/workflows/e2e.yml
  e2e/e2e.sh
Labels: size/M

#1084 doc: add database aggregate and operator
  docs/.vitepress/config.js
  docs/README.md
  docs/api/cloud.md
  docs/api/deploy-docker.md
  docs/api/function.md
  docs/doc-images/create-bucket.png
  docs/guide/cases/index.md
  docs/guide/cli/index.md
  docs/guide/client-sdk/index.md
  docs/guide/db/add.md
  docs/guide/db/aggregate.md
  docs/guide/db/command.md
  docs/guide/db/del.md
  docs/guide/db/find.md
  docs/guide/db/geo.md
  docs/guide/db/index.md
  docs/guide/db/operator.md
  docs/guide/db/policy.md
  docs/guide/db/quickstart.md
  docs/guide/db/update.md
  docs/guide/function/call-function-in-client.md
  docs/guide/function/call-function-in-http.md
  docs/guide/function/call-function.md
  docs/guide/function/depend.md
  docs/guide/function/env.md
  docs/guide/function/faq.md
  docs/guide/function/function-param.md
  docs/guide/function/index.md
  docs/guide/function/interceptor.md
  docs/guide/function/logs.md
  docs/guide/function/trigger.md
  docs/guide/function/use-function.md
  docs/guide/function/websocket.md
  docs/guide/index.md
  docs/guide/oss/get-sts.md
  docs/guide/oss/index.md
  docs/guide/oss/use-sts-in-client.md
  docs/guide/quick-start/Todo.md
  docs/guide/quick-start/login.md
  docs/guide/website-hosting/index.md
  docs/guide/website-hosting/quick-start.md
  docs/index.md
  docs/screenshots.md
Labels: size/XXL

#1087 perf(web): change upload folder to upload folder's files
  web/src/pages/app/storages/mods/UploadButton/index.tsx
Labels: size/XS

#1088 (docs)修改错别字 “按照”=>"安装"
  docs/guide/function/faq.md
Labels: size/XS

#1086 feat(web): add DocsPanel
  web/src/pages/app/functions/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
Labels: size/L

#1092 fix(web): function name regex
  web/src/components/Editor/FunctionEditor.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
Labels: size/S

#1091 fix(server): add regex validation for function name
  server/src/function/dto/create-function.dto.ts
Labels: size/XS

#1085 refactor(web): text overflow ellipsis
  web/src/components/Editor/JSONViewer.tsx
  web/src/pages/app/database/CollectionListPanel/index.tsx
  web/src/pages/app/database/PolicyListPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
Labels: size/S

#1090 compression all pictures and modify cloud storage introduction
  docs/.vitepress/config.js
  docs/doc-images/AppID.png
  docs/doc-images/add-env-step1.png
  docs/doc-images/add-env-step2.png
  docs/doc-images/add-env-step3.png
  docs/doc-images/add-env.png
  docs/doc-images/add-packages.png
  docs/doc-images/add-polocy.png
  docs/doc-images/appList.png
  docs/doc-images/application-list.png
  docs/doc-images/auto-build1.png
  docs/doc-images/auto-build2.png
  docs/doc-images/change-package-version.png
  docs/doc-images/cli-mind.png
  docs/doc-images/creat-polocy.png
  docs/doc-images/creat-token.png
  docs/doc-images/create-application.png
  docs/doc-images/create-bucket-1.png
  docs/doc-images/create-bucket.png
  docs/doc-images/create-cloudfunction.png
  docs/doc-images/create-function.jpg
  docs/doc-images/create-function.png
  docs/doc-images/create-gather.png
  docs/doc-images/create-injector.png
  docs/doc-images/db.png
  docs/doc-images/dblist.jpg
  docs/doc-images/delete-package.png
  docs/doc-images/doc-app-list.png
  docs/doc-images/doc-db.png
  docs/doc-images/doc-function-list.png
  docs/doc-images/doc-policy.png
  docs/doc-images/doc-storage.png
  docs/doc-images/edit-cloudfunction.png
  docs/doc-images/file.png
  docs/doc-images/function-body.png
  docs/doc-images/function-log.png
  docs/doc-images/function-query.png
  docs/doc-images/function-url.png
  docs/doc-images/function.png
  docs/doc-images/getToken-parseToken.png
  docs/doc-images/open-website.png
  docs/doc-images/package-list.png
  docs/doc-images/pakcage-list.jpg
  docs/doc-images/polocy-db-data.png
  docs/doc-images/publish-cloudfunction.png
  docs/doc-images/run-cloudfunction.png
  docs/doc-images/select-package-version.png
  docs/doc-images/todo-demo.png
  docs/doc-images/upload.png
  docs/doc-images/use-injector.png
  docs/doc-images/website-hosting.png
  docs/guide/oss/index copy.md
  docs/guide/oss/index.md
  docs/guide/oss/oss-by-function.md
Labels: size/L

#1094 fix(web): update error prompt of function name format
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
Labels: size/XS

#1093 chore(web): vite support dot path
  web/package-lock.json
  web/package.json
  web/src/components/CommonIcon/index.ts
  web/src/pages/homepage/language.tsx
  web/src/pages/homepage/navbar.tsx
  web/vite.config.ts
Labels: size/S

#1101 fix(web): fix bodyparams height
  web/src/components/Editor/JSONEditor.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
Labels: size/S

#1099 doc: added cloud storage subsequent documents and optimization documents overall structure
  docs/.vitepress/config.js
  docs/guide/db/index.md
  docs/guide/function/call-function-in-http.md
  docs/guide/function/env.md
  docs/guide/function/faq.md
  docs/guide/function/function-sdk.md
  docs/guide/function/index.md
  docs/guide/function/init.md
  docs/guide/function/logs.md
  docs/guide/function/use-function.md
  docs/guide/function/websocket.md
  docs/guide/oss/get-sts.md
  docs/guide/oss/index.md
  docs/guide/oss/oss-by-function.md
  docs/guide/oss/upload-by-function.md
  docs/guide/oss/use-sts-in-client.md
  docs/guide/website-hosting/index.md
Labels: size/XXL

#1100 doc: fix uniapp use client sdk example
  docs/guide/client-sdk/index.md
Labels: size/XS
