Repository labring/laf, pull requests merged in 2023-09, with the labels that each got.

#1504 fix(web): fix real-name auth
  web/src/layouts/Basic/RealNameWarn.tsx
  web/src/layouts/Basic/index.tsx
  web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/utils/request.ts
Labels: size/L

#1505 fix(server): change hpa metrics value
  server/src/instance/instance.service.ts
Labels: size/XS

#1502 feat(server): support query instant metrics
  e2e/2-monitor/00-query.test.ts
  server/src/monitor/dto/query-metrics.dto.ts
  server/src/monitor/monitor.controller.ts
  server/src/monitor/monitor.service.ts
  server/src/user/user.controller.ts
Labels: size/L

#1506 fix(web): fix monitor data instant undefined
  web/src/pages/app/mods/StatusBar/MonitorBar/index.tsx
Labels: size/XS

#1507 fix(server): no need to validate old phone when phone num miss
  server/src/user/user.controller.ts
Labels: size/M

#1509 fix(server): fix bind phone dto
  server/src/user/dto/bind-phone.dto.ts
  server/src/user/user.controller.ts
Labels: size/S

#1510 feat(web): optimize the list display logic
  web/src/pages/app/setting/AppMonitor/AreaCard/index.tsx
Labels: size/XS

#1511 fix(server): bind phone failed
  server/src/user/user.controller.ts
Labels: size/S

#1508 fix(web): fix real name auth shown by phone provider
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/layouts/Basic/index.tsx
  web/src/pages/app/setting/UserInfo/Mods/PhoneEditor.tsx
Labels: size/M

#1512 fix(web): increase zLevel of id verify warn
  web/src/layouts/Basic/RealNameWarn.tsx
Labels: size/XS

#1513 fix(web): fix miss getting providers
  web/src/layouts/Basic/index.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
  web/src/pages/auth/signin/index.tsx
Labels: size/S

#1517 fix(server): restart app when hpa canceled & fix conf publish
  server/src/application/application.controller.ts
  server/src/application/configuration.service.ts
Labels: size/XS

#1515 feat(web): enable daypicker component i18n
  web/src/components/DateRangePicker/index.tsx
  web/src/pages/app/setting/BillingDetails/index.tsx
  web/src/pages/app/setting/RechargeHistory/index.tsx
Labels: size/S

#1516 feat(web): optimize title style
  web/src/pages/app/setting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/AppMonitor/PieCard/index.tsx
Labels: size/S

#1498 feat(server): add user quota to limit user resource create
  server/src/application/application.controller.ts
  server/src/application/application.module.ts
  server/src/database/database.controller.ts
  server/src/database/database.module.ts
  server/src/database/database.service.ts
  server/src/database/entities/database-sync-record.ts
  server/src/initializer/initializer.service.ts
  server/src/user/entities/user-quota.ts
  server/src/user/quota.service.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
Labels: size/L

#1519 fix(web): fix storage list pagination & site available only storage readonly
  web/src/hooks/useAwsS3.ts
  web/src/pages/app/storages/mods/CreateWebsiteModal/SiteStatus.tsx
  web/src/pages/app/storages/mods/CreateWebsiteModal/index.tsx
  web/src/pages/app/storages/mods/FileList/index.tsx
  web/src/pages/app/storages/mods/StorageListPanel/index.tsx
  web/src/pages/app/storages/store.ts
Labels: size/L

#1520 refactor(web): configure site url settings
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/constants/index.ts
  web/src/layouts/Header/index.tsx
  web/src/pages/app/database/CollectionListPanel/index.tsx
  web/src/pages/app/functions/mods/AIChatPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/PromptModal.tsx
  web/src/pages/app/setting/UserSetting/index.tsx
  web/src/pages/homepage/contact.tsx
  web/src/pages/homepage/footer.tsx
  web/src/pages/homepage/joinus.tsx
  web/src/pages/homepage/navbar.tsx
  web/src/pages/homepage/status.tsx
  web/src/pages/homepage/video.tsx
  web/src/pages/siteSetting.ts
Labels: size/XL

#1521 fix(web): fix cron example & fix function page layout & hide email
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/layouts/Function.tsx
  web/src/pages/app/setting/UserInfo/index.tsx
Labels: size/M

#1523 feat(server): add laf web site settings
  server/src/initializer/initializer.service.ts
  server/src/setting/entities/setting.ts
Labels: size/M

#1526 feat(web): add laf web site settings
  web/src/constants/index.ts
  web/src/layouts/Header/index.tsx
  web/src/pages/app/functions/mods/AIChatPanel/index.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/setting/UserSetting/index.tsx
  web/src/pages/homepage/contact.tsx
  web/src/pages/homepage/footer.tsx
  web/src/pages/homepage/joinus.tsx
  web/src/pages/homepage/navbar.tsx
  web/src/pages/homepage/status.tsx
  web/src/pages/homepage/video.tsx
  web/src/pages/siteSetting.ts
Labels: size/L

#1525 feat(web): collection list sort
  web/src/pages/app/database/CollectionListPanel/index.tsx
Labels: size/XS

#1527 fix(cli): fix read function name error in windows
  cli/src/action/function/index.ts
Labels: size/XS

#1528 fix(server): add the user quota setting during initialization.
  server/src/initializer/initializer.service.ts
  server/src/setting/entities/setting.ts
  server/src/user/quota.service.ts
Labels: size/M

#1531 feat(server): add signup profit
  server/src/account/account.service.ts
  server/src/initializer/initializer.service.ts
  server/src/setting/entities/setting.ts
Labels: size/S

#1534 fix(server): fix user quota
  server/src/user/quota.service.ts
Labels: size/XS

#1535 fix(web): fix params not update & change function list type
  web/src/apis/typing.d.ts
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/store.ts
Labels: size/M

#1533 refactor(web): adjust editor fontsize & optimize function create modal
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/Editor/FunctionEditor.tsx
  web/src/constants/index.ts
  web/src/hooks/useHotKey.ts
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/functionTemplates.ts
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/customSetting.ts
  web/src/pages/globalStore.ts
Labels: size/L

#1536 feat(web): add client settings & change settings directory
  .vscode/settings.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/components/CommonIcon/index.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/constants/index.ts
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/setting/Profile/index.tsx
  web/src/pages/app/setting/SysSetting/AppEnvList/EditTextarea/index.tsx
  web/src/pages/app/setting/SysSetting/AppEnvList/index.tsx
  web/src/pages/app/setting/SysSetting/AppEnvList/service.ts
  web/src/pages/app/setting/SysSetting/AppInfoList/InfoDetail/index.tsx
  web/src/pages/app/setting/SysSetting/AppInfoList/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/PieCard/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/index.tsx
  web/src/pages/app/setting/SysSetting/CommonSetting/index.tsx
  web/src/pages/app/setting/SysSetting/CustomDomain/index.tsx
  web/src/pages/app/setting/SysSetting/CustomDomain/service.ts
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/app/setting/UserSetting/BillingDetails/index.tsx
  web/src/pages/app/setting/UserSetting/CardRedemption/index.tsx
  web/src/pages/app/setting/UserSetting/CardRedemption/service.ts
  web/src/pages/app/setting/UserSetting/PATList/DateSelector/index.module.scss
  web/src/pages/app/setting/UserSetting/PATList/DateSelector/index.tsx
  web/src/pages/app/setting/UserSetting/PATList/index.tsx
  web/src/pages/app/setting/UserSetting/PATList/service.ts
  web/src/pages/app/setting/UserSetting/PricingStandards/PricingCard.tsx
  web/src/pages/app/setting/UserSetting/PricingStandards/index.tsx
  web/src/pages/app/setting/UserSetting/RechargeHistory/index.tsx
  web/src/pages/app/setting/UserSetting/Usage/index.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/Mods/AvatarEditor.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/Mods/EmailEditor.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/Mods/PasswordEditor.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/Mods/PhoneEditor.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/Mods/UsernameEditor.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/index.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/service.ts
  web/src/pages/app/setting/UserSetting/UserInvite/index.tsx
  web/src/pages/app/setting/UserSetting/UserInvite/service.ts
  web/src/pages/app/setting/UserSetting/index.tsx
  web/src/pages/app/setting/UserSetting/useTabMatch.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/customSetting.ts
  web/src/pages/functionTemplate/FuncTemplateItem/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/index.tsx
Labels: size/L

#1537 refactor(web): change function list & revert create function
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
Labels: size/L

#1538 fix(web): fix files can't be accessed before refreshing & change file path
  web/src/pages/app/storages/mods/FileList/index.tsx
  web/src/pages/app/storages/store.ts
Labels: size/S

#1540 feat(cli): support database export and import
  cli/src/action/database/index.ts
  cli/src/action/function/index.ts
  cli/src/api/custom.ts
  cli/src/api/v1/account.ts
  cli/src/api/v1/application.ts
  cli/src/api/v1/authentication.ts
  cli/src/api/v1/billing.ts
  cli/src/api/v1/data-contracts.ts
  cli/src/api/v1/database.ts
  cli/src/api/v1/function.ts
  cli/src/api/v1/functiontemplate.ts
  cli/src/api/v1/group.ts
  cli/src/api/v1/monitor.ts
  cli/src/api/v1/public.ts
  cli/src/api/v1/recyclebin.ts
  cli/src/api/v1/user.ts
  cli/src/command/database/index.ts
  cli/src/main.ts
  cli/src/util/request.ts
Labels: size/XXL

#1544 fix(web): fix create function default code
  web/src/constants/index.ts
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
Labels: size/S

#1547 fix(web): fix style in npm deps list area (#1546)
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
Labels: size/XS

#1545 feat(web): add function list desc-name display & fix editor min-h
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/database/mods/DeleteCollectionModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/setting/SysSetting/CommonSetting/index.tsx
  web/src/pages/app/storages/mods/DeleteBucketModal/index.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/home/mods/DeleteAppModal/index.tsx
Labels: size/L

#1548 feat(server): add affinity settings in region
  server/src/initializer/initializer.service.ts
  server/src/instance/instance.service.ts
  server/src/region/entities/region.ts
Labels: size/M

#1539 feat(runtime): reuse context
  packages/cloud-sdk/src/function.interface.ts
  runtimes/nodejs/src/handler/debug-func.ts
  runtimes/nodejs/src/handler/invoke-func.ts
  runtimes/nodejs/src/support/function-engine/types.ts
Labels: size/L

#1551 Add auto-compact of apisix-etcd.
  build/charts/apisix/values.yaml
Labels: size/XS

#1555 fix(build): minio console ingress enable websocket
  build/charts/minio/templates/console-ingress.yaml
Labels: size/XS
