Repository labring/laf, pull requests merged in 2024-02, with the labels that each got.

#1836 fix(server): add environment variable to control bucket domain Create…
  server/src/constants.ts
  server/src/gateway/bucket-domain-task.service.ts
Labels: size/XS

#1825 feat(web): add function list context menu
  web/package-lock.json
  web/package.json
  web/src/components/ConfirmButton/index.tsx
  web/src/components/DateRangePicker/index.tsx
  web/src/components/MoreButton/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/ContextMenu/index.scss
  web/src/pages/app/functions/mods/FunctionPanel/ContextMenu/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/service.ts
  web/src/pages/app/setting/UserSetting/BillingDetails/index.tsx
  web/src/pages/app/setting/UserSetting/RechargeHistory/index.tsx
  web/src/pages/app/setting/UserSetting/index.tsx
Labels: size/L

#1824 feat(web): support updating dependencies without restarting
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/Editor/typesResolve/index.ts
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/UseTemplate/UseTemplateModal.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/UseTemplate/index.tsx
Labels: size/L

#1823 feat(runtime&server): support updating dependencies without restarting
  runtimes/nodejs/Dockerfile
  runtimes/nodejs/Dockerfile.init
  runtimes/nodejs/init.sh
  runtimes/nodejs/package.json
  runtimes/nodejs/src/support/database-change-stream/conf-change-stream.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/module-hot-reload.ts
  runtimes/nodejs/start.sh
  runtimes/nodejs/upload-dependencies.sh
  server/src/dependency/dependency.service.ts
  server/src/instance/instance.service.ts
Labels: size/L

#1817 docs: add local search and keep old docs temporarily
  .github/workflows/deploy-doc-deprecated.yml
  docs/.vitepress/config.mts
  docs/.vitepress/zh.mts
  docs/zh/cli/index.md
  docs/zh/client-sdk/index.md
  docs/zh/cloud-database/database-ql/add.md
  docs/zh/cloud-database/database-ql/aggregate.md
  docs/zh/cloud-database/database-ql/command.md
  docs/zh/cloud-database/database-ql/del.md
  docs/zh/cloud-database/database-ql/find.md
  docs/zh/cloud-database/database-ql/geo.md
  docs/zh/cloud-database/database-ql/index.md
  docs/zh/cloud-database/database-ql/operator.md
  docs/zh/cloud-database/database-ql/policy.md
  docs/zh/cloud-database/database-ql/quickstart.md
  docs/zh/cloud-database/database-ql/update.md
  docs/zh/quick-start/Todo.md
  docs_deprecated/.vitepress/config.js
Labels: size/M

#1841 chore(ci): fix deploy old docs
  .github/workflows/deploy-doc-deprecated.yml
Labels: size/XS

#1842 docs: fix redirect
  docs/.vitepress/config.mts
Labels: size/XS

#1855 fix(runtime): fix override deps when init package.json
  runtimes/nodejs/start.sh
  runtimes/nodejs/upload-dependencies.sh
Labels: size/XS

#1863 docs: fix uncorrect base link
  docs_deprecated/.vitepress/config.js
Labels: size/XS

#1860 Update login.md
  docs/zh/quick-start/login.md
Labels: size/XS

#1859 docs: improve macOS deploy guide
  deploy/README.md
  deploy/install-on-mac.sh
Labels: size/XS

#1861 feat(server): Add a setting to control whether WebPromoPage is enable…
  server/src/initializer/initializer.service.ts
  server/src/setting/entities/setting.ts
Labels: size/XS

#1858 feat(web): add index page setting config
  web/src/App.tsx
  web/src/pages/siteSetting.ts
  web/src/routes/index.tsx
Labels: size/M

#1868 chore(runtime-exporter): Optimize the build process
  .github/workflows/dockerize-runtime-exporter.yml
  services/runtime-exporter/Dockerfile
Labels: size/M

#1869 fix(runtime-exporter): Repairing the build process
  services/runtime-exporter/.dockerignore
Labels: size/XS

#1864 fix(web): fix storage path concatenation & add dependency install tip
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/storages/store.ts
Labels: size/M

#1865 feat(web): support auth methods of email
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/auth.ts
  web/src/components/CommonIcon/index.tsx
  web/src/components/DateRangePicker/index.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/TSEditor.tsx
  web/src/components/MoreButton/index.tsx
  web/src/constants/index.ts
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/functions/mods/DeployButton/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/ContextMenu/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/mods/HeadPanel/index.tsx
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/UserSetting/BillingDetails/index.tsx
  web/src/pages/app/setting/UserSetting/RechargeHistory/index.tsx
  web/src/pages/app/setting/UserSetting/UserInfo/index.tsx
  web/src/pages/app/storages/mods/FileList/index.tsx
  web/src/pages/auth/reset-password/index.tsx
  web/src/pages/auth/service.ts
  web/src/pages/auth/signin/index.tsx
  web/src/pages/auth/signin/mods/LoginByEmailPanel/index.tsx
  web/src/pages/auth/signin/mods/LoginByPasswordPanel/index.tsx
  web/src/pages/auth/signup/index.tsx
  web/src/pages/auth/store.ts
Labels: size/XL

#1867 feat(server): support auth methods of email
  server/src/authentication/dto/email-signin.dto.ts
  server/src/authentication/dto/passwd-reset.dto.ts
  server/src/authentication/dto/passwd-signup.dto.ts
  server/src/authentication/email/email.controller.ts
  server/src/authentication/email/email.service.ts
  server/src/authentication/entities/email-verify-code.ts
  server/src/authentication/user-passwd/user-password.controller.ts
  server/src/authentication/user-passwd/user-password.service.ts
  server/src/function/entities/cloud-function.ts
Labels: size/L

#1781 fix(server): billing for all apps including stopped apps
  server/src/application/application.service.ts
  server/src/billing/billing-creation-task.service.ts
  server/src/billing/billing-payment-task.service.ts
  server/src/billing/billing.service.ts
  server/src/instance/instance-task.service.ts
Labels: size/L

#1871 fix(server): Fix the problem that the certificate of unbundled websit…
  server/src/gateway/website-task.service.ts
Labels: size/XS
