Repository labring/laf, pull requests merged in 2024-03, with the labels that each got.

#1882 fix(server): fix too large entity error when upload large func
  server/src/main.ts
Labels: size/XS

#1877 feat(web): support ai code completion
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/TSEditor.tsx
  web/src/pages/app/setting/SysSetting/CommonSetting/index.tsx
  web/src/pages/customSetting.ts
  web/src/pages/siteSetting.ts
Labels: size/L

#1879 feat(server): recover the application and synchronize the recovery fu…
  server/src/database/database.service.ts
Labels: size/L

#1884 fix(server): fix extra billing for ddb when app has stopped
  server/src/billing/billing-creation-task.service.ts
Labels: size/XS

#1891 fix(runtime): fix upload-dependencies tar path
  runtimes/nodejs/upload-dependencies.sh
Labels: size/XS

#1887 fix(runtime): print error when invoke init function error
  runtimes/nodejs/src/support/init-hook.ts
Labels: size/XS

#1897 Update pagination.md
  docs/zh/cloud-database/query/pagination.md
Labels: size/XS

#1892 feat(server): add app network traffic metering
  server/src/billing/billing-creation-task.service.ts
  server/src/billing/billing.service.ts
  server/src/billing/dto/calculate-price.dto.ts
  server/src/billing/entities/network-traffic.ts
  server/src/constants.ts
  server/src/gateway/bucket-domain-task.service.ts
  server/src/main.ts
  server/src/system-database.ts
Labels: size/L

#1894 feat(web): add app network traffic metering
  web/src/apis/v1/api-auto.d.ts
  web/src/apis/v1/notification.ts
  web/src/pages/app/setting/UserSetting/BillingDetails/index.tsx
  web/src/pages/app/setting/UserSetting/PricingStandards/PricingCard.tsx
  web/src/pages/app/setting/UserSetting/PricingStandards/index.tsx
  web/src/pages/app/setting/UserSetting/Usage/index.tsx
  web/src/pages/app/setting/index.tsx
Labels: size/L

#1895 chore(cli): optimize ignoring projects
  cli/template/gitignore
Labels: size/XS

#1905 fix(web): fix pwa cache
  web/Dockerfile
  web/mime.types
  web/nginx.conf
  web/vite.config.ts
Labels: size/S

#1906 fix(server): fix dedicated database connect host
  server/src/database/dedicated-database/dedicated-database.service.ts
Labels: size/XS

#1907 fix(web): fix nginx conf
  web/Dockerfile
  web/mime.types
  web/nginx.conf
Labels: size/S

#1910 fix(runtime): fix storage server query url problem
  runtimes/nodejs/src/storage-server.ts
Labels: size/S

#1912 feat(web): remove charge input
  web/src/components/ChargeButton/index.tsx
Labels: size/XS
