Repository labring/laf, pull requests merged in 2024-01, with the labels that each got.

#1763 feat(web): add laf_doc and laf_about_us url config
  web/src/constants/index.ts
  web/src/layouts/Header/index.tsx
  web/src/pages/homepage/footer.tsx
  web/src/pages/homepage/navbar.tsx
  web/src/pages/siteSetting.ts
Labels: size/L

#1764 chore(server): add site settings
  server/src/initializer/initializer.service.ts
  server/src/setting/entities/setting.ts
Labels: size/S

#1754 feat(web): support version upgrade prompt
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/App.tsx
  web/src/components/UpgradePrompt/index.tsx
  web/tsconfig.json
  web/vite.config.ts
Labels: size/L

#1755 feat(web): support deleting multiple storage files
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/ConfirmDialog/index.tsx
  web/src/hooks/useAwsS3.ts
  web/src/pages/app/storages/mods/FileList/index.tsx
  web/src/pages/globalStore.ts
Labels: size/L

#1762 feat(web): support rename functions using dragging
  server/src/function-template/dto/create-function-template.dto.ts
  server/src/function/dto/create-function.dto.ts
  server/src/function/dto/update-function.dto.ts
  server/src/recycle-bin/cloud-function/dto/get-recycle-bin-functions.dto.ts
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/FileTypeIcon/index.tsx
  web/src/components/SectionList/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/store.ts
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddFunctionModal.tsx
Labels: size/XL

#1767 chore(runtime): add ctx.params
  runtimes/nodejs/src/support/engine/types.ts
  runtimes/nodejs/src/support/ws.ts
Labels: size/XS

#1768 fix(web): fix ddb not compactable with old app
  web/src/pages/app/mods/StatusBar/MonitorBar/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/index.tsx
  web/src/pages/app/setting/SysSetting/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/S

#1766 chore(web): hide database policy when no policy
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/database/PolicyDataList/index.tsx
  web/src/pages/app/database/PolicyListPanel/index.tsx
  web/src/pages/app/database/index.tsx
Labels: size/L

#1771 fix(server): fix being failed to find address when connect ddb
  server/src/database/dedicated-database/dedicated-database.service.ts
Labels: size/XS

#1774 fix(runtime): wait for db ready
  runtimes/nodejs/src/db.ts
  runtimes/nodejs/src/handler/router.ts
Labels: size/M

#1776 chore(runtime) fix runtime database connection
  runtimes/nodejs/src/support/cloud-sdk.ts
Labels: size/XS

#1775 chore(ci): add digest for runtime-init image
  .github/workflows/dockerize-runtime-nodejs.yml
Labels: size/XS

#1660 feat(runtime): add ts lsp server
  runtimes/nodejs/Dockerfile
  runtimes/nodejs/README.md
  runtimes/nodejs/functions/global.d.ts
  runtimes/nodejs/functions/tsconfig.json
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/handler/typings.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/support/lsp.ts
  runtimes/nodejs/start.sh
  server/src/function/dto/create-function.dto.ts
Labels: size/L

#1770 doc: fix display errors
  docs/zh/cloud-function/websocket.md
Labels: size/XS

#1777 fix(web): wait for all delete files promise settled
  web/src/pages/app/storages/mods/FileList/index.tsx
Labels: size/XS

#1778 docs: fix jwt token expiration time error
  docs/zh/cloud-function/auth.md
Labels: size/XS

#1783 Revert "feat(web): support function editor with lsp"
  .vscode/settings.json
  package.json
  web/package-lock.json
  web/package.json
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/components/EditableTable/EditableTr/index.tsx
  web/src/components/EditableTable/NormalTr/index.tsx
  web/src/components/EditableTable/index.module.scss
  web/src/components/EditableTable/index.tsx
  web/src/components/Editor/CodeViewer.tsx
  web/src/components/Editor/CommonDiffEditor.tsx
  web/src/components/Editor/ENVCodeEditor.tsx
  web/src/components/Editor/ENVEditor.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/JSONEditor.tsx
  web/src/components/Editor/LanguageClient.ts
  web/src/components/Editor/TSEditor.tsx
  web/src/components/Editor/TextModel.tsx
  web/src/components/Editor/index.css
  web/src/components/Editor/typesResolve/index.ts
  web/src/components/Editor/userWorker.ts
  web/src/components/TextButton/index.tsx
  web/src/constants/index.ts
  web/src/hooks/useFunctionCache.ts
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/DeployButton/index.tsx
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/index.tsx
  web/src/pages/app/functions/mods/HeadPanel/index.tsx
  web/src/pages/app/functions/store.ts
  web/src/pages/app/mods/StatusBar/LSPBar/index.tsx
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
  web/src/pages/app/mods/StatusBar/index.tsx
  web/src/pages/app/setting/SysSetting/AppEnvList/index.tsx
  web/src/pages/app/setting/SysSetting/AppEnvList/service.ts
  web/src/pages/app/setting/SysSetting/AppInfoList/index.tsx
  web/src/pages/app/setting/SysSetting/CommonSetting/index.tsx
  web/src/pages/app/setting/SysSetting/DatabaseMonitor/index.tsx
  web/src/pages/app/setting/index.tsx
  web/src/pages/customSetting.ts
  web/src/pages/functionTemplate/CreateFuncTemplate/Mods/AddEnvironmentsModal.tsx
  web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
  web/src/pages/globalStore.ts
  web/src/pages/home/mods/CreateAppModal/index.tsx
  web/src/types/index.d.ts
  web/src/utils/format.ts
  web/src/utils/streamFetch.ts
  web/vite.config.ts
Labels: size/XXL

#1790 chore(ci): ignore empty for sentry
  .github/workflows/dockerize-web.yml
Labels: size/XS

#1792 feat(server): add the create storage user task
  server/src/application/application-task.service.ts
  server/src/constants.ts
  server/src/storage/storage-user-task.service.ts
  server/src/storage/storage.module.ts
  server/src/storage/storage.service.ts
Labels: size/L

#1756 feat(server): support function history changelog
  server/src/function/dto/update-function.dto.ts
  server/src/function/entities/cloud-function-history.ts
  server/src/function/function.service.ts
Labels: size/S

#1757 feat(web): support function changelog
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/pages/app/functions/mods/DeployButton/index.tsx
  web/src/pages/app/functions/mods/VersionHistoryPanel/index.tsx
Labels: size/M

#1795 fix(web): fix editor theme override & init with value
  web/src/components/Editor/ENVCodeEditor.tsx
  web/src/components/Editor/FunctionEditor.tsx
  web/src/components/Editor/JSONEditor.tsx
  web/src/components/Editor/index.css
  web/src/pages/app/functions/mods/EditorPanel/index.tsx
  web/src/pages/app/setting/SysSetting/AppEnvList/index.tsx
Labels: size/L

#1793 fix(web): error when click recommend specs
  web/src/pages/home/mods/CreateAppModal/BundleControl/index.tsx
Labels: size/S

#1797 fix(server): billing error with old apps
  server/src/application/application.controller.ts
  server/src/billing/billing-creation-task.service.ts
Labels: size/M

#1798 fix(web): cannot click history func version
  web/src/pages/app/functions/mods/VersionHistoryPanel/index.tsx
Labels: size/M

#1799 fix(server): update function changelog optional
  server/src/function/dto/update-function.dto.ts
Labels: size/XS

#1800 fix(server): disable i18n file watching in server
  server/src/app.module.ts
Labels: size/XS

#1804 chore(cli): opt cli code prompt
  cli/package.json
  cli/src/action/application/index.ts
  cli/src/common/constant.ts
  cli/template/global.d.ts
  cli/template/response.d.ts
  cli/template/tsconfig.json
Labels: size/XXL

#1806 fix(server): update account updateAt
  server/src/account/account.controller.ts
  server/src/billing/billing-payment-task.service.ts
Labels: size/XS

#1802 fix(web): change diff editor to monaco-editor-react
  web/src/App.tsx
  web/src/components/Editor/CommonDiffEditor.tsx
  web/src/pages/app/functions/mods/DebugPanel/index.tsx
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
Labels: size/M

#1809 fix(web): fix monaco editor keyP binding
  web/src/components/Editor/FunctionEditor.tsx
Labels: size/S

#1814 fix(web): fix function scroll bar & support horizontal scrolling
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.module.scss
  web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
  web/src/pages/app/functions/mods/HeadPanel/index.tsx
Labels: size/M

#1816 chore: install-on-linux.sh change the sealos version 4.3.7
  deploy/install-on-linux.sh
Labels: size/XS

#1810 feat(web&server): control the activation of the ddb & change the location of deploy manifests
  build/charts/laf-server/templates/deployment.yaml
  build/charts/laf-server/values.yaml
  build/start.sh
  server/src/application/application.controller.ts
  server/src/constants.ts
  server/src/initializer/deploy-manifest/database.yaml
  server/src/initializer/initializer.service.ts
  server/src/region/entities/region.ts
  server/src/region/region.service.ts
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/apis/typing.d.ts
  web/src/pages/app/mods/StatusBar/MonitorBar/index.tsx
  web/src/pages/home/mods/CreateAppModal/DatabaseBundleControl/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/L

#1818 chore(server): separate bucket creation and bucket policy creation logic
  server/src/storage/bucket-task.service.ts
Labels: size/XS

#1811 feat(web): add logs pause button
  web/public/locales/en/translation.json
  web/public/locales/zh-CN/translation.json
  web/public/locales/zh/translation.json
  web/src/chakraThemeDark.ts
  web/src/components/CommonIcon/index.tsx
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
Labels: size/L

#1813 feat(runtime&server): support display error/log line
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/config.ts
  runtimes/nodejs/src/handler/invoke.ts
  runtimes/nodejs/src/index.ts
  runtimes/nodejs/src/support/engine/console.ts
  runtimes/nodejs/src/support/engine/module.ts
  runtimes/nodejs/src/support/engine/types.ts
  server/src/function-template/function-template.service.ts
  server/src/function/function.service.ts
  server/src/utils/lang.ts
Labels: size/L

#1820 fix(server): read manifests failed when init region
  server/nest-cli.json
  server/src/initializer/initializer.service.ts
Labels: size/S

#1819 feat(web): add storage sort & fix monitor data undefind
  web/src/components/CommonIcon/index.tsx
  web/src/hooks/useAwsS3.ts
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/SysSetting/DatabaseMonitor/AreaCard/index.tsx
  web/src/pages/app/storages/mods/FileList/index.tsx
Labels: size/L

#1821 fix(web): fix deploy not update recent function list & fix relative path file input
  web/src/apis/v1/api-auto.d.ts
  web/src/components/Editor/TSEditor.tsx
  web/src/components/Editor/typesResolve/index.ts
  web/src/pages/app/functions/mods/DeployButton/index.tsx
Labels: size/M

#1822 fix(build): remove unneeded build layer
  build/Kubefile
Labels: size/XS

#1828 fix(server): fix compiled code that doesn't support await import
  server/src/utils/lang.ts
Labels: size/XS

#1829 fix(server): fix certificate not deleting and rebuilding issue when u…
  server/src/gateway/runtime-domain-task.service.ts
Labels: size/XS

#1833 fix(cli): storage field key error during refresh
  cli/src/schema/app.ts
Labels: size/XS
