Repository labring/laf, pull requests merged in 2024-04, with the labels that each got.

#1936 docs: add sealaf migration docs
  docs/.vitepress/zh.mts
  docs/zh/doc-images/add-pat.png
  docs/zh/doc-images/sealos-website-hosting.png
  docs/zh/other/sealaf-migration.md
Labels: size/L

#1923 feat(runtime): support generating openapi docs
  runtimes/nodejs/package-lock.json
  runtimes/nodejs/package.json
  runtimes/nodejs/src/handler/openapi.ts
  runtimes/nodejs/src/handler/router.ts
  runtimes/nodejs/src/support/engine/cache.ts
  runtimes/nodejs/src/support/openapi.ts
  server/src/application/application.controller.ts
  server/src/function/function.service.ts
Labels: size/L

#1928 fix(web): fix monitor yaxis overflow
  web/src/pages/app/setting/SysSetting/AppMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/PieCard/index.tsx
  web/src/pages/app/setting/SysSetting/AppMonitor/index.tsx
  web/src/pages/app/setting/SysSetting/DatabaseMonitor/AreaCard/index.tsx
  web/src/pages/app/setting/SysSetting/DatabaseMonitor/PieCard/index.tsx
  web/src/pages/app/setting/SysSetting/DatabaseMonitor/index.tsx
Labels: size/M

#1939 fix(web): add database policy add modal back
  web/src/pages/app/database/PolicyDataList/index.tsx
  web/src/pages/app/database/PolicyListPanel/index.tsx
Labels: size/M

#1954 feat(server) fix error cannot read properties of undefined
  server/src/storage/storage-user-task.service.ts
Labels: size/XS

#1940 feat: log request server automatically send an empty message
  server/src/log/log.controller.ts
Labels: size/XS

#1957 feat(runtime): ws add url to param
  runtimes/nodejs/src/support/ws.ts
Labels: size/XS

#1947 feat(web): recommend function template config with templateid
  web/src/pages/app/functions/mods/FunctionPanel/CreateModal/index.tsx
Labels: size/M
