Repository labring/laf, pull requests merged in 2024-06, with the labels that each got.

#1991 fix(web): fix the issue where function type parsing is attempted befo…
  web/src/components/Editor/TSEditor.tsx
Labels: size/S

#1973 fix(runtime): zombie processes caused by inappropriate way of dependencies
  runtimes/nodejs/src/support/module-hot-reload.ts
Labels: size/S

#1994 fix(web): adjust transparency of the overlay for application startup …
  web/src/pages/app/mods/StatusBar/LogsModal/initLog.tsx
Labels: size/XS

#2000 chore(web&server): make the number of database replicas can be changed
  server/src/application/application.controller.ts
  web/src/pages/app/mods/StatusBar/LogsModal/initLog.tsx
  web/src/pages/home/mods/CreateAppModal/DatabaseBundleControl/index.tsx
  web/src/pages/home/mods/CreateAppModal/index.tsx
Labels: size/S

#2012 chore(runtime&web): dependency changes require application restart
  runtimes/nodejs/src/support/database-change-stream/conf-change-stream.ts
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/functions/mods/DependencePanel/index.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/UseTemplate/UseTemplateModal.tsx
  web/src/pages/functionTemplate/Mods/TemplateInfo/UseTemplate/index.tsx
  web/src/pages/globalStore.ts
Labels: size/L

#2013 chore(web): Optimize log display logic
  web/src/pages/app/functions/mods/DependencePanel/AddDependenceModal/index.tsx
  web/src/pages/app/mods/StatusBar/LogsModal/index.tsx
  web/src/pages/app/mods/StatusBar/LogsModal/initLog.tsx
Labels: size/M

#2014 chore(web): fix bouns display
  web/src/components/ChargeButton/index.tsx
Labels: size/XS
